### ISSUE TITLE
Pool with zstd breaks grub scripts

### ISSUE THREAD

**Issue by hyegeek** [openzfs/zfs#11805] opened 2021-03-26 19:27 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Gentoo
Distribution Version	| Stable
Linux Kernel	| 5.10.23
Architecture	| x86_64
ZFS Version	| 2.0.4-r0-gentoo
SPL Version	| 2.0.4-r0-gentoo

### Describe the problem you're observing
The grub script run during a grub-mkconfig fail to correctly create the root= option for booting a ZFS root system that has zstd compression. The boot partition is an ext3 partition and not part of the the zfs pool.
### Describe how to reproduce the problem
zfs set compression=zstd pool
grub-mkconfig -o /boot/grub/grub.cfg
### Include any warning/errors/backtraces from the system logs

No errors or warnings, but the root= option is set to root=ZFS=/root instead of root=ZFS=pool/root.

**Comment by bghira** [comment] 2021-04-04 17:02
grub doesn't support it, so, it won't detect it.

**Comment by bghira** [comment] 2021-04-04 17:03
also for what it's worth this is resolved in Ubuntu although you have to use their specific initramfs code and filesystem layout with UUIDs set appropriately in relevant ZFS user properties.

**Comment by nabijaczleweli** [comment] 2021-04-04 17:49
You can use my patch from [Debian #848945](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848945#30) to use the bootfs. I won't be submitting it to upstream becuase lol GNU project but you're more than welcome to be vaguely inspired by it and submit something similar.

**Comment by hyegeek** [comment] 2021-04-04 19:07
The solution I used for my setup was a little simpler and not generic. Thanks for the patch ideas for a  more generic solution.

The bigger reason for opening the issue is that even when you turn zstd off, the pool remains invisible to grub. That seems like something that should at least be warned about.

**Comment by nabijaczleweli** [comment] 2021-04-04 19:52
it's laid out quite clearly in [zpool-features(5)](https://github.com/openzfs/zfs/blob/bf169e9f15efbc343b931f20cfad5d2b59c8a821/man/man5/zpool-features.5#L1062), innit?

**Comment by rlaager** [comment] 2021-04-04 20:40
This isn't an OpenZFS problem. The reality of GRUB not supporting all features is why e.g. the Debian/Ubuntu Root-on-ZFS HOWTOs recommend a separate bpool.

**Closed by rlaager** 2021-04-04 20:40 UTC
Labels: Status: Triage Needed, Type: Defect

**Comment by mjanssens** [comment] 2021-04-04 21:26
Sorry if I'm proposing something silly, but could #11468 help here in any way, in terms of preventing that nonsupported features get enabled when creating or upgrading a pool?

**Comment by rlaager** [comment] 2021-04-04 21:33
> Sorry if I'm proposing something silly, but could #11468 help here in any way, in terms of preventing that nonsupported features get enabled when creating or upgrading a pool?

Yes, that is exactly what it is for. So if GRUB compatibility is important, you can set compatible=grub (or whatever it ended up being). In this case, it would prevent you from (inadvertently) enabling zstd. But if zstd is what you want, then you will be incompatible with GRUB and need some other approach (use a separate bpool or use something other than GRUB).

**Comment by mskarbek** [comment] 2021-04-04 22:31
`systemd-boot` and single EFI partition mounted as `/boot` works fine when you are dealing with EFI-based system.

**Comment by bghira** [comment] 2021-04-04 23:58
unfortunately without some mucking about using ZFS EFI drivers you can't put ESP on ZFS.. which means we're not able to snapshot /boot or rollback, etc. so while, yes, it works, the suggestion isn't very "helpful" in context of making ZFS work without hackish workarounds like efi-stub or kernel on FAT partition.

**Comment by hyegeek** [comment] 2021-04-05 01:24
A separate bpool is no help if you have zstd as grub will still fail to recognize root. I have a separate disk with ext3 and that's what is failing to correctly be setup by grub. You simply can't use zstd if you want grub to play nice.

**Comment by maxximino** [comment] 2021-04-05 21:28
I have an ugly workaround (works on Debian Sid at least) for having a root pool with whatever features I want:
in /etc/default/grub: 
GRUB_CMDLINE_LINUX_DEFAULT="root=ZFS=fastpool/rootfs_debian"

the issue is that grub needs to understand the boot pool of course, but has no business in understanding the root pool except at the time of generating the grub.conf.

Overall my cmdline looks like this:
$ cat /proc/cmdline 
BOOT_IMAGE=/vmlinuz-5.10.0-5-amd64 root=ZFS=/rootfs_debian ro root=ZFS=fastpool/rootfs_debian

the parameter is specified twice, but luckily it's parsed in the correct order by Debian's initramfs. (that's why "ugly workaround")
