### ISSUE TITLE
ZoL not really willing to evict caches from RAM when needed

### ISSUE THREAD

**Issue by Harvie** [openzfs/zfs#6740] opened 2017-10-09 01:14 UTC
I have overall impression that when ZFS allocates some memory (eg. for L1ARC) it will NOT free it up fast enough if needed by processes. When other filesystems on Linux cache something it gets evicted from cache as soon as some process needs memory.

However with L1ARC (and possibly other ZFS caches) it will lead to OOM (or even full system crash and reboot) once there is not enough memory/swap for processes. Even when i had 30 GB of data cached (which in my opinion can be droped from cache almost immediately). This makes my system very unstable and effectively means you can really subtract zfs_arc_max from your total system memory, it's no use anymore. which is not nice in my opinion.

Also in htop the cache memory used by ZFS is "green" like for "process" memory rather than "yellow" for "cache". Which indicates that something about ZFS caching is kinda arrogant (in terms of memory allocation).

**Comment by MyPod** [comment] 2017-10-09 18:54
It could be useful to have the specs for your system as in the template for the issue. I can vouch for htop showing zfs (v0.7.2)'s ARC as cache and memory being freed up when needed. IIRC there was an issue for zfs < 0.7.2 and kernels > 4.4.0 where the ARC memory usage would not be reported correctly, but this has been fixed in 0.7.2.

I also suspect that despite your attempt to terminate `zdb -S`, some kernel thread kept running the command in the background making your system memory starved. Knowing more about the system and condition in which this happened will likely help in figuring if that's the case.

**Comment by Harvie** [comment] 2017-10-10 01:54
Proxmox VE 5.0 (Debian 9 - Stretch), HP ProLiant DL160 g7

```
filename:       /lib/modules/4.10.17-3-pve/zfs/zfs.ko
version:        0.6.5.11-1
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
srcversion:     B9DC860740C2225772C1B4F
```
```
  pool: tank
 state: ONLINE
  scan: scrub repaired 0 in 12h14m with 0 errors on Sun Oct  8 12:38:35 2017
config:

	NAME                            STATE     READ WRITE CKSUM
	tank                            ONLINE       0     0     0
	  mirror-0                      ONLINE       0     0     0
	    sda                         ONLINE       0     0     0
	    sdb                         ONLINE       0     0     0
	logs
	  wwn-0x50026b723a0354f8-part5  ONLINE       0     0     0
	cache
	  wwn-0x50026b723a0354f8-part6  ONLINE       0     0     0

errors: No known data errors
```
log+cache = SSD

**Comment by jwittlincohen** [comment] 2017-10-16 21:28
Memory management should be considerably better in 0.7.  I had similar issues on a desktop system with 16GB of RAM where ZFS would not release memory fast enough when starting up VMs in KVM/QEMU.  However, I haven't had any issues with 0.7.0-0.7.2.

**Comment by adamdmoss** [comment] 2020-08-06 03:07
I believe this is fixed quite effectively by 3442c2a02d1b506d100914f056fc1686771f04da - @ahrens  ?

**Comment by ahrens** [comment] 2020-08-06 04:11
I think we've made substantial improvements in this area.  I wouldn't be surprised if there's still more work to do, but I think we're better off closing this bug, and if we notice problems with the new code then we'll collect info about them in new bugs.

**Closed by ahrens** 2020-08-06 04:11 UTC

**Comment by Harvie** [comment] 2020-08-06 06:41
Nice to hear about succesful improvements guys! Can i expect these fixes to get released soon?

**Comment by Harvie** [comment] 2020-08-06 06:50
BTW is there reason why `htop` cannot differentiate between L1ARC cache and process memory? Is that bug in htop? Or is it caused by ZFS using same allocator as processes do rather than some cache-specific allocation api?

**Comment by ahrens** [comment] 2020-08-06 18:12
`htop` would need to be taught about the ZFS ARC specifically.  Without any special knowledge, it should show up the same as other kernel memory allocations (not process memory - but I'm not sure that htop differentiates between kernel and process memory).

**Comment by Atrate** [comment] 2021-12-26 22:26
I don't know how severe the issue used to be, but I can say that now a similar issue still happens — with high memory pressure caused by ARC caches, `arc_evict` is not quick enough to evict caches, causing `kswapd0` to kick in and thrashing ensues. This also happens in swapless systems, with clean pages being the target of kswapd in that case.
