### ISSUE TITLE
gpg check fails on upgrade to Fedora 37

### ISSUE THREAD

**Issue by jmurayama** [openzfs/zfs#14221] opened 2022-11-23 21:41 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| 36
Kernel Version	| 6.0.7-200.fc36
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.6-1

### Describe the problem you're observing
dnf system-upgrade download fails on upgrade to Fedora 37
### Describe how to reproduce the problem
sudo dnf system-upgrade download --allowerasing --refresh --releasever=37
### Include any warning/errors/backtraces from the system logs

```
GPG key at file:///etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux (0xF14AB620) is already installed
The GPG keys listed for the "ZFS on Linux for Fedora 37" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: zfs-debuginfo-2.1.6-2.fc37.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
Public key for libnvpair3-2.1.6-2.fc37.x86_64.rpm is not installed. Failing package is: libnvpair3-2.1.6-2.fc37.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
Public key for libuutil3-2.1.6-2.fc37.x86_64.rpm is not installed. Failing package is: libuutil3-2.1.6-2.fc37.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
Public key for libzfs5-2.1.6-2.fc37.x86_64.rpm is not installed. Failing package is: libzfs5-2.1.6-2.fc37.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
Public key for libzfs5-devel-2.1.6-2.fc37.x86_64.rpm is not installed. Failing package is: libzfs5-devel-2.1.6-2.fc37.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
Public key for libzpool5-2.1.6-2.fc37.x86_64.rpm is not installed. Failing package is: libzpool5-2.1.6-2.fc37.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
Public key for zfs-2.1.6-2.fc37.x86_64.rpm is not installed. Failing package is: zfs-2.1.6-2.fc37.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
Public key for zfs-debugsource-2.1.6-2.fc37.x86_64.rpm is not installed. Failing package is: zfs-debugsource-2.1.6-2.fc37.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
Public key for zfs-dkms-2.1.6-2.fc37.noarch.rpm is not installed. Failing package is: zfs-dkms-2.1.6-2.fc37.noarch
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
Public key for zfs-dracut-2.1.6-2.fc37.noarch.rpm is not installed. Failing package is: zfs-dracut-2.1.6-2.fc37.noarch
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```

**Comment by tonyhutter** [comment] 2022-11-23 22:35
Duplicate of: https://github.com/openzfs/zfs/issues/14201

**Closed by tonyhutter** 2022-11-23 22:35 UTC
Labels: Type: Defect
