### ISSUE TITLE
zfs recv -o encryption doesn't work with -R

### ISSUE THREAD

**Issue by rincebrain** [openzfs/zfs#13533] opened 2022-06-02 11:40 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| 11
Kernel Version	| 5.10.0-14-amd64
Architecture	| x86_64
OpenZFS Version	| b9d98453f

### Describe the problem you're observing
I thought this has been filed, and it's kind of touched on by #11017, but not too explicitly, so...
```
$ dd if=/dev/urandom of=/foo/bar/1 bs=1M count=1;
$ zfs snapshot foo/bar@snap1; 
$ zfs snapshot foo/bar@snap2;
$ zfs send -R foo/bar@snap2 | zfs recv -o encryption=on -o keylocation=file:///somekey -o keyformat=raw foo/baz;
cannot receive incremental stream: encryption property 'encryption' cannot be set for incremental streams.
```

This seems like it should be fixable, but it's just one more rough spot.

### Describe how to reproduce the problem
Above.

### Include any warning/errors/backtraces from the system logs
N/A

**Comment by bghira** [comment] 2022-06-05 15:43
you are better off never using `-R`. it is too big of a hammer for automated scripts. for instance, resuming `-R` sends is almost impossible without already rewriting the implementation of `-R` in your replication script using `for` loops over the list of child datasets. the resume tokens only resume from the snapshot that the transfer died on, and it will not continue from there.

after the send dies, `-R` can not be used to resume it. you may as well go back and do the full send from the beginning if that `-R` is so important. otherwise,


to send the initial dataset:
```bash
[DEBUG] send_filesystem: cmd: sudo zfs destroy -Rv tank/backup2/rpool 2>&1
[DEBUG] send_filesystem: cmd: sudo zfs send -Levw  rpool@1654442101 | mbuffer -m 128M | sudo zfs recv -s   -o canmount=noauto -o special_small_blocks=0  tank/backup2/rpool
```

this is an encrypted dataset. it's a parent dataset that has encrypted children in it, so we raw send the whole thing. no special recv side options are needed, the 'special_small_blocks' simply keeps the special vdev clean on my backup box, and `canmount` prevents it from making a mess at startup when all the backups try to mount.

here's what it looks like once received:

```
% zfs list -r tank/backup2 -o name,encryptionroot,encryption        
NAME                            ENCROOT             ENCRYPTION
tank/backup2/rpool              tank/backup2/rpool  aes-256-gcm
```

it is its own encroot, meaning, we sent it with its key.

to send the children fresh:

```bash
[DEBUG] send_filesystem: cmd: sudo zfs send -Lev  rpool/ROOT@1654442101 | mbuffer -m 128M | sudo zfs recv -s   -o canmount=off -o special_small_blocks=0 -x encryption tank/backup2/rpool/ROOT
```

don't use `-w` on the children, or `-p`. instead, they have to use `-x encryption` on the recv side so they remain linked to the parent:

```bash

% zfs list -r tank/backup2 -o name,encryptionroot,encryption        
NAME                            ENCROOT             ENCRYPTION
tank/backup2/rpool              tank/backup2/rpool  aes-256-gcm
tank/backup2/rpool/ROOT         tank/backup2/rpool  aes-256-gcm
tank/backup2/rpool/ROOT/gentoo  tank/backup2/rpool  aes-256-gcm
```

the child has the parent as its encroot.

if you send a clone, you'll have to add `-o origin=foo/bar` to the recv side so that the origin is linked correctly.

overall it's a good idea to avoid `-R` because it can incorrectly link origins. it searches the local fs tree by guid instead of having an idea of the path it needs to look for. the only way to provide the correct path is with `recv -o origin=...`

**Comment by bghira** [comment] 2022-06-05 15:46
the downside of the approach above is that it requires the key to be loaded on the recv side for the encroot to be linked correctly.

if you need blind backups unfortunately **there is (currently) no way** to link them so that they all unlock with a single key.

`-R|-p` and `-w`, and recv side argument `-o` are all pretty much mutually exclusive.

**Comment by bghira** [comment] 2022-06-05 15:51
oh, it just occurred to me, you're trying to use `-R` to send unencrypted datasets into an encrypted recv side. I am not really familiar with that procedure, but it's going to suffer a lot of the same issues with `-R`.

**Comment by rincebrain** [comment] 2022-06-05 15:54
I am familiar with the many downsides of -R, yes.

As it turns out, though, I haven't heard anyone propose removing it, so bug reports against it still seem reasonable.

**Comment by bghira** [comment] 2022-06-05 17:31
sure, I wasn't implying that this is an invalid bug, or that it shouldn't be fixed. moreover, i understand that you're becoming more adept at contributing fixes, so I wouldn't even put it past you to be able to submit a fix for this.

I was just providing an in-depth workaround and examples from my own experiences for anyone who comes along and wants to make this work. it took me a fair bit of time to set up those examples and obtain the output, and then my system even crashed during that because of some ZAP-related bug I've hit every now and then, so I had to redo it.

all that said, for anyone else, i would suggest not to rely on this being fixed in timely manner, and to implement some kind of workaround.

**Comment by rincebrain** [comment] 2022-06-05 17:56
"you're becoming more adept at contributing fixes" comes across as pretty condescending. I would ask that you consider talking down to people less.

I'm curious to know more about the ZAP-related bug you're describing - is it one that's already open, or yet another exciting notch on the encryption bugs wall?

**Comment by bghira** [comment] 2022-06-05 17:58
sorry, no. it was intended as a compliment. i will disengage from this.

**Comment by pepsinio** [comment] 2022-08-23 17:42
Same issue. Sometimes i feel that zfs is built on chopsticks.  Very fundamental scenarios do not work. First was #12659 and now this. I cannot get a working backup strategy one year in.

**Comment by rincebrain** [comment] 2022-08-23 17:47
Most of ZFS is pretty well engineered.

I personally am just treating the native encryption code as unmaintained at this point, though, and would advise most other people do the same.

**Closed** 2022-12-14 01:30 UTC
Labels: Type: Defect, Component: Send/Recv, Component: Encryption
