### ISSUE TITLE
Module build fails on aarch64 due to using GPL-only symbol

### ISSUE THREAD

**Issue by imrehg** [openzfs/zfs#14555] opened 2023-03-01 03:28 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch Linux ARM
Distribution Version	| rolling
Kernel Version	| 6.2.1
Architecture	| aarch64
OpenZFS Version	| zfs-2.1.9-1

### Describe the problem you're observing

Failing to compile kernel module for zfs.

### Describe how to reproduce the problem

Try building the zfs dkms module on the device.

### Include any warning/errors/backtraces from the system logs

```terminal
$ sudo dkms autoinstall
[...snip...]
  MODPOST /var/lib/dkms/zfs/2.1.9/build/module/Module.symvers
ERROR: modpost: GPL-incompatible module zcommon.ko uses GPL-only symbol 'kernel_neon_begin'
ERROR: modpost: GPL-incompatible module zcommon.ko uses GPL-only symbol 'kernel_neon_end'
ERROR: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'kernel_neon_end'
ERROR: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'kernel_neon_begin'
make[2]: *** [scripts/Makefile.modpost:138: /var/lib/dkms/zfs/2.1.9/build/module/Module.symvers] Error 1
make[1]: *** [Makefile:1973: modpost] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.2.1-1-aarch64-ARCH/build'
make: *** [Makefile:55: modules-Linux] Error 2
make: Leaving directory '/var/lib/dkms/zfs/2.1.9/build/module'
```

**Comment by rincebrain** [comment] 2023-03-01 09:56
Yes, it appears they broke it deliberately in torvalds/linux@aaeca98456431a8d9382ecf48ac4843e252c07b3, first in 6.2.

> Given the limited existing deployment of non-GPL modules for arm64 and the
> fact that other architectures like x86 already make their equivalent
> functions GPL only this is not expected to be disruptive to existing users.

Uh-huh.

**Comment by imrehg** [comment] 2023-03-01 13:17
Good find, cheers! Well, this is a bummer, I guess a kernel downgrade for the time being and then we'll see...

Anything you suggest that I can help, or comment, put in a word as support anywhere?

**Comment by ryao** [comment] 2023-03-01 14:24
You could email `Mark Brown <broonie@kernel.org>` and `Will Deacon <will@kernel.org>` telling them that they were wrong about the change not being "disruptive to existing users". Those symbols are guarding CPU instructions and marking them GPL exported just means that those that want to use FP/SIMD inside the kernel needs to call those instructions themselves. `EXPORT_SYMBOL_GPL()` is not meant to bar non-GPL modules from accessing trivial helper functions.

As for what x86 does, it originally had been `EXPORT_SYMBOL()`, new functionally identical symbols with `EXPORT_SYMBOL_GPL()` markings were introduced, everything in the tree was switched to them and then original symbols were dropped. When end users complained, people simply cited the kernel policy about not removing symbols not being used inside the tree, even though it had effectively been changing a pair of symbols that were long under `EXPORT_SYMBOL()` to `EXPORT_SYMBOL_GPL()`. The maintainers refused to restore access to the original functionality by putting the new symbols under `EXPORT_SYMBOL()`, even though the symbols were guarding trivial functionality.

**Comment by microcai** [comment] 2023-03-06 08:53
time to license openzfs as GPL !

**Comment by rincebrain** [comment] 2023-03-06 09:52
You understand that a lot of OpenZFS's codebase is owned by Oracle, right, and can't be relicensed by anyone working on it?

**Comment by ryao** [comment] 2023-03-06 14:16
@microcai The OpenZFS codebase is owned by hundreds of stakeholders that would all need to sign off on a license change. As a consequence, doing a license change is impossible.

That said, many stakeholders would be against a change to the GPL 2.0 (or any version of the GPL for that matter). Going with BSD-2 would be far more likely, but the CDDL has the benefit of a patent grant, so this likely would be unrealistic while there are patents held by Oracle and IBM that apply to the OpenZFS codebase.

**Comment by eirnym** [comment] 2023-03-10 00:13
I'm sorry for an angry comment, but why not to put all the symbols under GPL in Linux kernel? This will solve all Linux problems by burying the Linux completely for those who want to use non-GPL licence in drivers.

**Comment by jittygitty** [comment] 2023-03-11 02:37
> time to license openzfs as GPL !

No, not at all! Time to just BUILD ZFS as if it is GPL, we have every right to do that:
https://github.com/openzfs/zfs/issues/11357

Far as I'm concerned this should be promoted in our documentation and any/all GPL-ONLY exports that can be used, should be used when we do that. If you are not "distributing", you can do whatever you want on your own machine. Have fun!

**Comment by jittygitty** [comment] 2023-03-11 03:45
@eirnym I would prefer we keep license discussions separate from bug reports etc (but those I opened were "closed"), so to answer your question, anyone can still use even closed source proprietary drivers with Linux even if all exports are GPL_ONLY, and the GPL protects even that right.  

You are not supposed to "distribute" it mixed, but you can mix Linux with "whatever" you want, the end user is the KING according to GPL philosophy.

Ironically, the Linux Kernel folks aren't doing any damage to "proprietary" closed-source software, they just use a "CONDOM" ie shim GPL driver that sits in-between their proprietary driver and the Linux kernel. Such "condom" usage is unstoppable.

Kernel devs have complained of condoms, but I've never seen them do anything about it "legally" in the courts. Perhaps because they feared the result if they lost?

Even if they won, at most they'd win against distribution of systems that come with Linux and proprietary drivers (GPU?) and their condoms, "shipped/distributed" together. They can NEVER stop any user from using any condoms and GPU or other proprietary drivers they want, so it's sad that they hurt open-source projects more.

The good news is that if you BUILD your own ZFS modules you can simply change CDDL to GPL (as per #11357 ) and be done with it. We don't need no "condoms" : )

**Comment by jittygitty** [comment] 2023-03-11 04:46
@ryao "Having the Linux kernel relicensed would be more realistic. Linus Torvalds has enough influence among Linux copyright holders that he could likely get a license change done if he really wanted to do it." -ryao

Although I myself had not too long ago started writing a generic loosely COPYLEFT LICENSE that could bring blessed matrimony between Linux and other Copyleft projects, it would not be necessary for Linux to change its license to a more generic copyleft license, though that'd be great. Here's a SIMPLE easy fix for Symbol issues:

Ask Linus Torvalds to simply consider changing:
"EXPORT_SYMBOL_GPL" to "EXPORT_SYMBOL_COPYLEFT".

I have joked about making such a pull request before, see https://github.com/openzfs/zfs/issues/11357#issuecomment-1118003748

Then under "COPYLEFT" the Linux Kernel could accept weak copyleft licenses like CDDL and many other copyleft licenses (even GPLv3!) as "copyleft" compliant.

Think about it, currently, GPLv3 kernel modules are just as INCOMPATIBLE (distribution-wise and Export-Symbol-wise) with the Linux Kernel as PROPRIETARY "closed source" kernel modules/drivers (GPU etc). Copyleft CDDL is in same boat.

Why should LINUS do this? To prove that what he does aligns with the philosophy he claims to have been holding to! He has always said he just wants anyone using and modifying his code to be released in source code form, he was very vocal against changing Linux Kernel from GPLv2 to GPLv3 because he had NO PROBLEM with "Tivoization". But with change I proposed, he could:

1. Keep Kernel License in his preferred GPLv2 license, tivoization compatible. 
2. Make GPLv3 modules and other copyleft (CDDL/ZFS) able to use ALL SYMBOLS.
3. Make a "much stronger" case against PROPRIETARY "source-closed" drivers.

So since "EXPORT_SYMBOL_GPL" was not supposed to hurt other OPEN-SOURCE (even copyleft) projects, but was always by his own claims to be against "closed-source" drivers, what better way to prove this than EXPORT_SYMBOL_COPYLEFT?

**Comment by ryao** [comment] 2023-03-11 17:47
@jittygitty While this is an interesting conversation, I have two thoughts:

1. This is perhaps not an appropriate forum for it. A discussion in the discussions tab might be a better place: https://github.com/openzfs/zfs/discussions/new?category=general
2. I suspect that you will get push back from mainline on this because the GPL symbols are marked such under a theory that anything using them is probably a derived work of Linux and must be subject to the GPLv2. That is not really true, but it is a line that they have drawn that permits development to proceed without the distraction of a constant debate over this. Your proposal is likely to reignite that debate, so be prepared for that.

That said, I would prefer that this issue stay on the topic of how we will handle this latest compatibility issue. If an email has not been sent to the Linux ARM maintainers yet, please include me on CC in that email. You can find my email in my github profile.

**Comment by eirnym** [comment] 2023-03-11 17:55
@jittygitty Thank you for a long answer with a good explanation. it is a useful for those who don't know. My comment was mostly rhetorical, as I'm personally aware about this problems and solutions.

**Comment by jittygitty** [comment] 2023-03-14 23:52
@ryao I haven't done directly or indirectly what I had "joked" about because it's NOT the best way to do it. Perhaps I should put a warning here the only/best way to get some love for all copyleft (like ZFS) from Linux and more specifically LINUS:

Linus is more understanding and more likely to be conciliatory than some of the newer kernel devs or even his right-hand team who might out of reflex jump and say something negative that will make progress difficult without losing face etc.

So, if anyone wants to propose anything similar to what I proposed, you MUST contact LINUS in PRIVATE and ideally he should KNOW YOU or at least know of you and already have "some" professional respect for you. Then you can propose to him something in-line to what I said, to change symbols so that he allows for more loosely COPYLEFT licenses like ZFS since it still lives up to his claimed purposes throughout his career and would do so without hurting other copyleft projects.

IF you can do the above in private, and then agree you will then follow-up in PUBLIC via a medium/LWN.net/Kernel/etc I think you may win LINUS over, since I don't think he wants to look like a hypocrite, and I think he genuinely doesn't want to hurt other open-source projects. BUT if you don't go through him/Linus first, privately, its going to be extremely difficult if his right-hand team does some knee-jerk response, because he can't then publicly contradict them and mess up his relationship with them, which is of higher importance to him. That's my advice.

If LINUS comes out with an extended hand in good consideration of such proposal and the conversation is made public, his right-hand team and kernel devs will be respectful of his direction and I think they will become friendlier to the idea as well. 

After all, I don't think anyone has really proposed to them what I proposed, which has no compromise on their preferred license but brings harmony with all copyleft. 
So, if they actually pause and think about it and realize the benefits, there's hope :)

And ryao like I said, this license discussion should be in another thread, but ask those who "closed" my other 'license' threads. (To kinda well "bury" open talk?)

Also, since this specific issue is a "victim" of these licensing issues, its pertinent.

**Comment by jittygitty** [comment] 2023-03-15 00:20
I forgot to answer: "...how we will handle this latest compatibility issue"? Are you ok with what I already proposed? Change CDDL to GPL and build. Simplest fix, isn't it?

I don't see any problem with that myself. I'm not saying we can't "also" try to do some other more complicated workaround (but potential regressions again etc?)

**Comment by mabod** [comment] 2023-03-19 06:14
I tested this and it works fine. No message like "module license 'CDDL' taints kernel." anymore in the journal.
I added a patch to my zfs-dkms PKGBUILD which replaces CDDL with GPL in the META file. That was it.

**Comment by imrehg** [comment] 2023-03-19 08:14
@ryao I've followed your recommendation and sent an email to the developers of that patch, let's see what we hear back. Apologies that it took this long. I do agree with you that either a revert in the kernel (longshot) or significant OpenZFS development effort (long time) are proper solutions. Thanks for the additional context in your comment above, that helped to frame things better.

**Comment by eirnym** [comment] 2023-03-19 09:11
@jittygitty @ryao would double-licensed kernel communication part helps. Or this is a CONDOM mentioned above and it's not strictly legal?

**Comment by mabod** [comment] 2023-03-19 14:19
I have a question for the experts. 

Someone can patch the kernel to replace EXPORT_SYMBOL_GPL with EXPORT_SYMBOL. What happens if this person distributes this patched kernel as binary and source code? My understanding is, that this does not violate the GPL. It is a simple code change but not a license change. 

The intentions, the morale, the philosophy behind the existence of EXPORT_SYMBOL_GPL doesn't matter from a legal point of view. Taking out EXPORT_SYMBOL_GPL might hurt the feelings of some kernel developers. But would it have legal implications?  I believe no. The only thing that matters from a legal point of view is the GPL. And that is not violate with such a patched kernel.

**Comment by eirnym** [comment] 2023-03-19 14:43
@mabod would a "statistical" user patch every kernel in every distribution just for ZFS usage? 

Gentoo distribution is more patch-friendly than Debian, Ubuntu, Fedora or RHEL

**Comment by mabod** [comment] 2023-03-19 14:46
First of all, I am just thinking out loud here. The idea would be to provide a binary kernel for a given distro. And creating the patched source code is fairly easy by scripting an `sed -i 's/EXPORT_SYMBOL_GPL/EXPORT_SYMBOL/g'` for a files in the source tree.

**Comment by eirnym** [comment] 2023-03-19 14:51
@mabod found an old discussion on that: https://lwn.net/Articles/154602/

**Comment by jittygitty** [comment] 2023-03-21 01:28
@mabod Yes you are right that "anything" inside the code of Linux kernel can be changed and even distributed since it is GPL after all. But PLEASE do not go down that path, it would create un-needed animosity. Stick to CDDL to GPL in META file.

@eirnym Yes and as you also pointed out about usual/statistical Linux user..., we can much simpler simply ;) give them option to run a "patch" at build to change ZFS CDDL to "GPL" and then build as mabod already confirmed worked just fine.

I elaborated more to ryao on this licensing topic in a private email.
@ryao Did you get my email?

**Comment by tomchiverton** [comment] 2023-04-09 16:06
Does the subject / initial post need updating, as this effects (at least) Fedora as well ?

**Comment by rincebrain** [comment] 2023-04-09 18:52
Since the symbols in question are ARM-specific, the subject at least is fine. I don't think mentioning it affects other distros is especially necessary, since it's a generic problem with Linux upstream.

**Comment by RaitoBezarius** [comment] 2023-04-19 06:58
Would ZFS be interested into a patch to provide a ZFS replacements for these functions so we can move on this issue? I am considering reverting the breaking kernel patch in NixOS like we did for AMD64 long time ago (https://www.phoronix.com/news/NixOS-Linux-5.0-ZFS-FPU-Drop), I would prefer to avoid any hostility towards the kernel but visibly the code was once there, so it does not seem that problematic.

**Comment by RaitoBezarius** [comment] 2023-04-19 06:59
Would ZFS be interested into a patch to provide a ZFS replacements for these functions so we can move on this issue? I am considering reverting the breaking kernel patch in NixOS like we did for AMD64 long time ago (https://www.phoronix.com/news/NixOS-Linux-5.0-ZFS-FPU-Drop), I would prefer to avoid any hostility towards the kernel but visibly the code was once there, so it does not seem that problematic.

**Comment by eirnym** [comment] 2023-04-19 13:57
@RaitoBezarius I like the idea

**Comment by jittygitty** [comment] 2023-04-19 22:58
@RaitoBezarius But why bother with such a patch and risk further friction with Linux kernel devs, when no one here will be upset if you simply change CDDL to GPL in META file and build. Because in the long run it could be more work to "maintain" such patches" to Linux kernel code versus the easy path of replace CDDL with GPL.

**Comment by RaitoBezarius** [comment] 2023-04-19 23:01
> @RaitoBezarius But why bother with such a patch and risk further friction with Linux kernel devs, when no one here will be upset if you simply change CDDL to GPL in zfs META file and build. Because in the long run it could be more work to "maintain such patches" to Linux kernel code versus the easy path of replace CDDL with GPL.

I work on the NixOS distribution, we cannot change CDDL to GPL in zfs META file, this is an outright violation, right?

**Comment by RaitoBezarius** [comment] 2023-04-19 23:07
> @RaitoBezarius No it is not, if you are "building" and "not" distributing it, you are free to do it. You can even give people a script they can use or a "flag" to build config. Simply do not "distribute" the zfs code itself with CDDL changed to GPL. But doing it via config flags or script during building is perfectly fine, no one will mind.
> 
> For further info on this please see my old issue/post #11357

We are a **Linux distribution**, we **do distribute** the binaries.

**Comment by RaitoBezarius** [comment] 2023-04-19 23:14
DKMS in the usual sense of other distributions does not make sense in the NixOS context. This is getting offtopic. ;)

**Comment by jittygitty** [comment] 2023-04-19 23:14
@RaitoBezarius I do not see any problem at all if your Linux "distribution" has scripts that "download" Linux kernel from somewhere and ZFS from somewhere, and then does s/CDDL/GPL/g on zfs META file before building zfs kernel modules.

**Comment by RaitoBezarius** [comment] 2023-04-19 23:18
> @RaitoBezarius I do not see any problem at all if your Linux "distribution" has scripts that "download" Linux kernel from somewhere and ZFS from somewhere, and then does s/CDDL/GPL/g on zfs META file before building zfs kernel modules.

NixOS has metadata for all packages' licenses, we cannot have a derivation that changes the derivation internal metadata dynamically and pretend that ZFS is CDDL, this is a legal compliance violation in our metadata.
We need to have a ZFS derivation that says it's GPL (which is false), and this is an outright violation.

This is not an acceptable solution in any way in nixpkgs.

> If you want to distribute the "binaries" of ZFS together with Linux kernel, Ubuntu I think didn't think there was an issue with that either. Some have argued that upon "building", the cddl zfs "binary" in reality becomes a GPL binary.

In that case, the revert patch solution is as good because "some have argued" that an old revision of code is still usable ;).

**Comment by jittygitty** [comment] 2023-04-19 23:20
@RaitoBezarius Yes in your case, then perhaps your solution makes sense. The problem is that for most others here who build their own zfs, it really is not a good solution. For those users, the CDDL to GPL solution is better in several ways.

**Comment by dylanmtaylor** [comment] 2023-04-20 04:20
> time to license openzfs as GPL !

It can't be done unless Oracle is 110% on-board.

**Closed** 2024-01-09 00:05 UTC
Labels: Type: Defect
