### ISSUE TITLE
Ask for confirmation before destroy unclean pool

### ISSUE THREAD

**Issue by Harliff** [openzfs/zfs#9171] opened 2019-08-16 04:30 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Proxmox
Distribution Version	| 6.0
Linux Kernel	| 5.0.15-1-pve
Architecture	| x86_64
ZFS Version	| 0.8.1-pve1
SPL Version	| 0.8.1-pve1 

### Describe the problem you're observing
zpool destroy running without asking for confirmation, even an fs/volumes exist inside it.
It is possible to destroy production pool instead of e.g. test pool due to mistake.  

It's better destroy non-clean pools only with -F ("force") switch.

### Describe how to reproduce the problem
zpool create mypool /dev/sdb
zfs create mypool/important-data
zpool destroy mypool

**Comment by behlendorf** [comment] 2019-08-16 17:27
Assuming nothing else has used the devices, a destroyed pool can be re-imported using the `zpool import -D` option described in the man page. 

```
            -D      Imports destroyed pools only.  The -f option is also
                     required.
```

**Comment by martellini** [comment] 2019-08-17 17:37
#4134

**Comment by Harliff** [comment] 2020-08-24 21:22
> Assuming nothing else has used the devices, a destroyed pool can be re-imported using the `zpool import -D` option described in the man page.

Didn't know that. Thanks!

**Comment by gmelikov** [comment] 2020-08-24 21:26
I'll close this issue as a duplicate of more general one #4134

**Closed by gmelikov** 2020-08-24 21:26 UTC

**Comment by erikschul** [comment] 2025-02-03 17:48
Important to note: IIUC `zpool import -D` will import the pool, but the datasets are lost.
