### ISSUE TITLE
zfsprops(7) reference to the Snapshots section of zfsconcepts(7) links to the wrong page (self-referencing)

### ISSUE THREAD

**Issue by grahamperrin** [openzfs/zfs#14868] opened 2023-05-14 22:56 UTC
### Describe the problem you're observing

Under <https://openzfs.github.io/openzfs-docs/man/7/zfsprops.7.html#snapdir>: 

> … as discussed in the [Snapshots](https://openzfs.github.io/openzfs-docs/man/7/zfsprops.7.html#Snapshots) section of [zfsconcepts(7)](https://openzfs.github.io/openzfs-docs/man/7/zfsconcepts.7.html). …

* the first of the two links refers to the wrong page (zfsprops(7) has no such section)
* the second is OK.

**Comment by gmelikov** [comment] 2023-05-15 08:00
Duplicate of https://github.com/openzfs/openzfs-docs/issues/251

**Closed by gmelikov** 2023-05-15 08:00 UTC
Labels: Type: Defect

**Comment by grahamperrin** [comment] 2023-05-16 18:08
Thanks, and my apologies for using the wrong repo.
