### ISSUE TITLE
user dropped to shell if  if boot dataset has mountpoint=legacy

### ISSUE THREAD

**Issue by ofthesun9** [openzfs/zfs#14599] opened 2023-03-09 18:16 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	|bookworm
Distribution Version	|12
Kernel Version	|6.1.0-5-amd64
Architecture	|amd64
OpenZFS Version	|2.1.9 (debian 2.1.9-2)

### Describe the problem you're observing
booting (I am using ZFSBootMenu) a dataset where mountpoint=legacy is not working anymore 

The boot cmdline sets root=zfs:rpool/ENCR/MISC/machines/bookworm

As far as I get it, the zfs script provided by zfs-initramfs should be
```
# Last hail-mary: Hope 'rootmnt' is set!
if [ "$mountpoint" = "legacy" ]; then
          ZFS_CMD="mount.zfs"
mountpoint=""
fi
```	
instead of	
```
# Last hail-mary: Hope 'rootmnt' is set!
mountpoint=""
if [ "$mountpoint" = "legacy" ]; then
           ZFS_CMD="mount.zfs"
fi
```

This fixed my issue.

**Comment by rincebrain** [comment] 2023-03-09 19:01
mountpoint=legacy, or mountpoint=none?

because if you have mountpoint=legacy, that change shouldn't affect you, and if you don't, then you probably mean mountpoint=none, and you want #14473, I believe.

**Comment by ofthesun9** [comment] 2023-03-09 19:52
I do have mountpoint=legacy
I am using "debian" pakage 2.1.9-2 which is adding some patches issued after the 2.1.9 release

I think that the commit https://github.com/openzfs/zfs/commit/eb823cbc76d28a7cafdf6a7aafdefe7e74fe26bc is the cause of my issue.
the line 363 should be after the "if" statement (lines 364 365 366)

**Comment by rincebrain** [comment] 2023-03-09 20:01
Ah, I see. It took me a few reads to notice the problem here. Oh bother.

I don't know if your change is correct either, actually, since I'm pretty sure resetting that in both cases was intended, it's just the conditional being broken by doing so that's the problem...so I think moving the set below the if-fi entirely would work too.

@freqlabs, it seems like #14473 (and #14455) are incorrect because you clear mountpoint right before checking it. Is there some reason the if can't be above that?

**Comment by ryao** [comment] 2023-03-10 01:40
For some reason, people's eyes (mine included) skipped over that line when reviewing this. I agree that the `mountpoint=""` line should be deleted.

@ofthesun9 Would you open a PR with your change?

**Comment by ryao** [comment] 2023-03-10 02:01
@ofthesun9 Embarassingly, this was missed by our eyes (mine included) during review. Please open a PR with your change so that we can get it merged. It looks good to me.

**Closed** 2023-03-14 23:40 UTC
Labels: Type: Defect
