### ISSUE TITLE
BRT: cross-dataset block cloning fails with EXDEV on Linux 6.11

### ISSUE THREAD

**Issue by intelfx** [openzfs/zfs#16837] opened 2024-12-04 06:50 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch
Distribution Version	| current
Kernel Version	| 6.11.10
Architecture	| x86_64
OpenZFS Version	| 2.3.0-rc3

### Describe the problem you're observing

Similarly to concerns from #405 (https://github.com/openzfs/zfs/issues/405#issuecomment-1746628010), attempting to do a `cp --reflink=always` between two sibling datasets fails with EXDEV. However, unlike that case, no encryption is used.

### Describe how to reproduce the problem

```console
# ccat /sys/module/zfs/parameters/*clone*
/sys/module/zfs/parameters/zfs_bclone_enabled     1
/sys/module/zfs/parameters/zfs_bclone_wait_dirty  1

# modprobe brd rd_nr=1 rd_size=$(bscalcq -k '50G')

# CFG_ZPOOL_CREATE_OPTS=(
        -o ashift=12
        -o feature@block_cloning=enabled
        -O compression=lz4
        -O acltype=posixacl -O xattr=sa -O dnodesize=auto
)
# zpool create "${CFG_ZPOOL_CREATE_OPTS[@]}" test /dev/ram0
# parallel zfs create -p ::: test/ROOT/test{1,2,3,4}
# parallel "dd if=/dev/urandom of=/test/ROOT/test{}/file{} bs=1M count=1024" ::: 1 2 3 4
# zpool sync test

# cp -a --reflink=always /test/ROOT/test2/file2 /test/ROOT/test4/file4
/usr/bin/cp: failed to clone '/test/ROOT/test4/file4' from '/test/ROOT/test2/file2': Invalid cross-device link
```

**Comment by amotin** [comment] 2024-12-04 10:42
@intelfx Could you similar to quoted post run `strace` on the `cp` to make sure what sysctl fails there?  Just to make sure it uses `copy_file_range()`, since other system calls have that limitation on kernel level.

**Comment by snajpa** [comment] 2024-12-04 11:38
AFAIK this isn't supported (due to the reason @intelfx) so I'd say it's more of a Feature request than a Defect (how can one change it?)

**Comment by robn** [comment] 2024-12-04 11:45
@intelfx yes, this is the reason.

Duplicate of #15345.

**Closed by robn** 2024-12-04 11:45 UTC
Labels: Type: Defect
