### ISSUE TITLE
FTBFS on ppc64le with ieee-long-double toolchain

### ISSUE THREAD

**Issue by gyakovlev** [openzfs/zfs#14308] opened 2022-12-21 08:14 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| gentoo
Distribution Version	| rolling
Kernel Version	| 5.15.80
Architecture	| ppc64le
OpenZFS Version	| 2.1.7 and today's master

### Describe the problem you're observing
compiler/libc (both clang and gcc) are configured with 128bit long double.

(gcc built with --with-long-double-format=ieee ./configure switch)

zfs fails to build with that toolchain:

gcc error is not very helpful:
```
../../module/zfs/vdev_raidz_math_powerpc_altivec_common.h:30:23: error: expected '(' before '__volatile__'
   30 | #define __asm __asm__ __volatile__
```

clang produces much more helpful output:
```
./../module/zfs/vdev_raidz_math_powerpc_altivec_common.h:30:23: note: expanded from macro '__asm'                                                                                                                                                             
#define __asm __asm__ __volatile__                                                                                              
                      ^                                         
In file included from ../../module/zfs/vdev_raidz_math_powerpc_altivec.c:203:
In file included from ../../include/sys/vdev_raidz_impl.h:29:                                                                   
In file included from ../../lib/libspl/include/sys/debug.h:30:
In file included from ../../lib/libspl/include/assert.h:32:   
In file included from ../../lib/libspl/include/stdio.h:27: 
In file included from /usr/include/stdio.h:896:           
/usr/include/bits/stdio-ldbl.h:78:1: error: meaningless 'volatile' on asm outside function
__LDBL_REDIR_DECL (vasprintf)                                                                                                   
^                                                               
/usr/include/sys/cdefs.h:569:31: note: expanded from macro '__LDBL_REDIR_DECL'
  extern __typeof (name) name __asm (__ASMNAME ("__" #name "ieee128"));       
                              ^                                                                                                 
../../module/zfs/vdev_raidz_math_powerpc_altivec_common.h:30:23: note: expanded from macro '__asm'
```

### Describe how to reproduce the problem
ppc64le system, pass `-mabi=ieeelongdouble` to compiler, or have it configured to implicitly do it by default.

removing that `__volatile__` on single line allows build to complete.

**Comment by gyakovlev** [comment] 2022-12-21 19:10
fedora recently switched to 128bit float long double for ppc64le
https://fedoraproject.org/wiki/Changes/PPC64LE_Float128_Transition

gentoo is in the process of switching too, this will become more visible soon.

**Comment by gyakovlev** [comment] 2022-12-21 21:00
I'm still investigating on my side, this might be glibc bug.

kernel part of zfs builds fine, it's failure in userspace build.

similar to:

https://patchwork.sourceware.org/project/glibc/patch/20221116150803.1990947-1-tuliom@ascii.art.br/

or 

https://github.com/bminor/glibc/commit/d0fa09a770

**Comment by ryao** [comment] 2023-01-12 16:17
> I'm still investigating on my side, this might be glibc bug.

It is not a glibc bug. The issue is that the author did a hack to avoid explicitly marking inline assembly as volatile and it ended up affecting an external assembly declaration.

I find it weird to even have external assembly declarations. Usually, you could implement that just by pretending the assembly is compiled C code and following the appropriate calling convention.

That said, I have opened #14384 with a fix for this.

**Closed** 2023-01-13 18:59 UTC
Labels: Type: Defect
