### ISSUE TITLE
ZoL 0.7.13 + Linux Kernel 5.0.4: GPL-incompatible module zfs.ko uses GPL-only symbol 'preempt_schedule_notrace'

### ISSUE THREAD

**Issue by grahamc** [openzfs/zfs#8545] opened 2019-03-29 00:08 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| NixOS
Distribution Version	| 19.03 (beta)
Linux Kernel	|  5.0.4
Architecture	| aarch64-linux
ZFS Version	| 0.7.13
SPL Version	| 0.7.13

### Describe the problem you're observing

Kernel module build fails in MODPOST:

```
  LD [M]  /build/source/module/zfs/zfs.o
  Building modules, stage 2.
  MODPOST 7 modules
FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'preempt_schedule_notrace'
```

I'm also seeing the following warnings:

```
In file included from /build/source/module/zfs/vdev_raidz_math_aarch64_neon.c:30:0:
/build/source/module/zfs/vdev_raidz_math_aarch64_neon_common.h:126:0: warning: "ASM_BUG" redefined
 #define ASM_BUG() ASSERT(0)
```

```
                 from /build/source/module/zfs/vdev_raidz_math_aarch64_neon.c:26:
/nix/store/avplvw4j265f6brz3g368sqrlzkyabas-linux-5.0.4-dev/lib/modules/5.0.4/source/arch/arm64/include/asm/asm-bug.h:52:0: note: this is the location of the previous definition
 #define ASM_BUG() ASM_BUG_FLAGS(0)
```

```
In file included from /build/source/module/zfs/vdev_raidz_math_aarch64_neonx2.c:29:0:
/build/source/module/zfs/vdev_raidz_math_aarch64_neon_common.h:126:0: warning: "ASM_BUG" redefined
 #define ASM_BUG() ASSERT(0)
```

```
                 from /build/source/module/zfs/vdev_raidz_math_aarch64_neonx2.c:29:
/nix/store/avplvw4j265f6brz3g368sqrlzkyabas-linux-5.0.4-dev/lib/modules/5.0.4/source/arch/arm64/include/asm/asm-bug.h:52:0: note: this is the location of the previous definition
 #define ASM_BUG() ASM_BUG_FLAGS(0)
```

### Describe how to reproduce the problem

Attempt to compile the module. In this particular case, if you have a machine with [Nix](https://nixos.org/nix) running aarch64:

```
nix-build https://github.com/nixos/nixpkgs/archive/23fd1394dc6bef03a2ff010278a24403a97f0647.tar.gz --system aarch64-linux -A linuxPackages_5_0.zfs
```

**Comment by grahamc** [comment] 2019-03-29 00:46
5.0.3 / 0.7.13 has the same problem: `nix-build https://github.com/nixos/nixpkgs/archive/bf3c19558244f038dce7993274da241e72e03da1.tar.gz --system aarch64-linux -A linuxPackages_5_0.zfs`

**Comment by grahamc** [comment] 2019-03-29 01:30
and:

- 0.7.13 / 5.0.2 (`nix-build https://github.com/nixos/nixpkgs/archive/e6b124b3b57eb327f777349086a8a67325f6c949.tar.gz --system aarch64-linux -A linuxPackages_5_0.zfs`)
- 0.7.13 /  5.0.1 (`nix-build https://github.com/nixos/nixpkgs/archive/2aa471997fd485a0678acb4b5d470da2f8eebbcb.tar.gz --system aarch64-linux -A linuxPackages_5_0.zfs`)

**Comment by nilsmeyer** [comment] 2019-03-29 13:29
As far as I can tell this has always been `EXPORT_SYMBOL_GPL`, did you set `CONFIG_PREEMPT`?

**Comment by grahamc** [comment] 2019-03-29 13:35
Hmm, yeah ... Not sure what is going on there. I do have `CONFIG_PREEMPT` set, attached is the full config.

[config.txt](https://github.com/zfsonlinux/zfs/files/3022846/config.txt)

**Comment by grahamc** [comment] 2019-03-29 13:59
The last time NixOS was able to build ZFS on aarch64 for the latest stable was 4.19.12, I'll start bisecting.

**Comment by grahamc** [comment] 2019-03-29 22:48
I bisected 5.0 to 4.19 and https://github.com/torvalds/linux/commit/0e9da3fbf7d81f0f913b491c8de1ba7883d4f217 is the first offending commit

Based on `git merge-base b12a912 00203ba` (the two parents of 0e9da3f), I've tried bisecting [40e020c129cfc991e8ab4736d2665351ffd1468d to 00203ba40d40d7f33857416adfb18adaf0e40123](https://github.com/torvalds/linux/compare/40e020c129cfc991e8ab4736d2665351ffd1468d...00203ba40d40d7f33857416adfb18adaf0e40123) but both ends built just fine.

My colleague is rebasing https://github.com/torvalds/linux/commit/0e9da3fbf7d81f0f913b491c8de1ba7883d4f217 on to https://github.com/torvalds/linux/commit/b12a9124eeb71d766a3e3eb594ebbb3fefc66902 and I'll be bisect that next.

**Comment by grahamc** [comment] 2019-03-30 05:11
OK I finished that rebase, and it narrowed down to this commit: https://github.com/torvalds/linux/commit/7fcf2b033b84e261dca283bc2911aaea4b07b525 -- calling it a day for now, and will look more tomorrow.

**Comment by grahamc** [comment] 2019-03-30 13:45
Attached are build logs and the results of the original attempted build (`nix-build https://github.com/nixos/nixpkgs/archive/23fd1394dc6bef03a2ff010278a24403a97f0647.tar.gz --system aarch64-linux -A linuxPackages_5_0.zfs`)

 - [nix-build-zfs-kernel-0.7.13-5.0.4.drv-0.log](https://github.com/zfsonlinux/zfs/files/3025494/nix-build-zfs-kernel-0.7.13-5.0.4.drv-0.log)
 - [nix-build-zfs-kernel-0.7.13-5.0.4.drv-0.tar.gz](https://github.com/zfsonlinux/zfs/files/3025495/nix-build-zfs-kernel-0.7.13-5.0.4.drv-0.tar.gz).

**Comment by behlendorf** [comment] 2019-04-03 22:14
@grahamc thanks for isolating the offending commit.  It looks like when they switched over to using percpu_ref's in `blkg_tryget()` they inadvertently converted it to the GPL-only symbol.  This looks to be specific to the way preemption is handled on aarch64.

This code is pulled in though the `CONFIG_BLK_CGROUP` option.  So if you can live without this functionality you could try disabling it until we find a good way to handle this.

**Comment by grahamc** [comment] 2019-04-04 00:47
Ah, excellent! Unfortunately, I can't turn that off so that workaround doesn't apply for me. However, I'm able to use 4.19 for the the next 4-5 months.

**Comment by vcunat** [comment] 2019-04-04 07:30
So, in NixOS we give up on ZFS in latest-kernel stuff for aarch64? ([example](https://hydra.nixos.org/job/nixos/release-19.03/nixos.iso_minimal_new_kernel.aarch64-linux/all))

**Comment by grahamc** [comment] 2019-04-04 11:38
Something like that, but let's move that discussion to our own issue tracker https://github.com/NixOS/nixpkgs/issues/58959 :)

**Comment by behlendorf** [comment] 2019-05-07 22:04
@grahamc I've opened PR #8725 which resolves the `ASM_BUG` warnings you observed when compiling for aarch64.  Regarding the original `preempt_schedule_notrace` issue, I discovered that neither the stock Fedora 29 or Ubuntu 19.04 aarch64 kernels encountered this issue.  The reason for this is they set `CONFIG_PREEMPT_VOLUNTARY=y` instead of `CONFIG_PREEMPT=y` in their kernel config.  Would this be a viable solution for NixOS?

**Comment by nilsmeyer** [comment] 2019-05-08 09:45
I'm also wondering if this may be a general issue with `CONFIG_PREEMPT` or only on aarch64?

**Comment by behlendorf** [comment] 2019-05-08 17:30
> may be a general issue with CONFIG_PREEMPT

This does look like it may be a general issue, but I haven't confirmed that.  The `ASM_BUG` fix has been committed and we'll back port it to 0.7.14.

**Comment by lheckemann** [comment] 2019-05-08 19:23
I'm currently checking if this also occurs on x86_64 with `CONFIG_PREEMPT=y`.

**Comment by lheckemann** [comment] 2019-05-08 20:35
This doesn't seem to affect my x86_64 build of the kernel — either it's truly an aarch64-specific issue, or there are some other config settings involved.

**Comment by nilsmeyer** [comment] 2019-05-08 22:17
So the build should probably fail if aarch64 && CONFIG_PREEMPT? At the very least a better error message can be displayed.

**Comment by behlendorf** [comment] 2019-05-08 22:28
That's a good idea.  This is something we could catch earlier at configure time.

**Comment by lheckemann** [comment] 2019-05-09 07:12
Yes, but also only from 5.0 onwards.

**Comment by pfremm** [comment] 2019-09-04 05:26
I am having this same issue on kernel 5.1 and ZoL 0.8.1.  I am running aarch64 as well.  Does any fix or workaround exist besides recompiling kernel or is that my only option?

**Comment by pfremm** [comment] 2019-09-05 02:56
@behlendorf I did see your patch was in masterline, and with CONFIG_PREEMPT set to 'Y' I still get the same build error on 5.1 kernel

**Comment by behlendorf** [comment] 2019-09-05 21:05
For aarch64 you'll want to rebuild your kernel for now.  No other easy fix currently exists.

**Comment by crocket** [comment] 2019-09-09 05:07
Does it affect PREEMPT_RT_FULL? I haven't tested real-time linux kernel on Raspberry Pi 3 B+, yet.

**Comment by prometheanfire** [comment] 2019-09-15 02:40
I seem to be hitting this on aarch64 with a kernel config set to `CONFIG_PREEMPT_NONE` in the kconfig (but not running config)

**Comment by prometheanfire** [comment] 2019-09-15 20:10
also of note, I was trying to install zfs master on 5.2.14

**Comment by satmandu** [comment] 2020-05-02 22:20
Is there any chance of the issue with ```preempt_schedule_notrace``` on aarch64 being tracked down further? I'm still seeing it with the other preempt patch in https://github.com/openzfs/zfs/pull/10209  with a 5.4.x kernel. and PREEMPT set:
```
# CONFIG_PREEMPT_NONE is not set
# CONFIG_PREEMPT_VOLUNTARY is not set
CONFIG_PREEMPT=y
CONFIG_PREEMPT_COUNT=y
CONFIG_PREEMPTION=y
CONFIG_PREEMPT_RCU=y
CONFIG_PREEMPT_NOTIFIERS=y
CONFIG_DEBUG_PREEMPT=y
CONFIG_PREEMPTIRQ_TRACEPOINTS=y
# CONFIG_PREEMPTIRQ_EVENTS is not set
# CONFIG_PREEMPT_TRACER is not set
# CONFIG_PREEMPTIRQ_DELAY_TEST is not set
```
```
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zfs/qat_crypt.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zfs/vdev_raidz_math_aarch64_neon.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zfs/vdev_raidz_math_aarch64_neonx2.o
  LD [M]  /var/lib/dkms/zfs/0.8.4/build/module/zfs/zfs.o
  Building modules, stage 2.
  MODPOST 8 modules
FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'preempt_schedule_notrace'
make[4]: *** [scripts/Makefile.modpost:94: __modpost] Error 1
make[3]: *** [Makefile:1607: modules] Error 2
make[3]: Leaving directory '/usr/src/linux-headers-5.4.35-v8+'
make[2]: *** [Makefile:30: modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/zfs/0.8.4/build/module'
make[1]: *** [Makefile:841: all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/0.8.4/build'
make: *** [Makefile:710: all] Error 2
```

**Comment by prometheanfire** [comment] 2020-07-13 15:49
this seems fixed in git master, building against 5.7.8

**Comment by jinnko** [comment] 2020-07-17 12:25
Building master didn't work on Aarch64 with kernel 5.4.49 using Armbian on a NanoPi M4v2.  

This is the final output:

```
  Building modules, stage 2.
  MODPOST 8 modules
FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'preempt_schedule_notrace'
make[6]: *** [scripts/Makefile.modpost:94: __modpost] Error 1
make[5]: *** [Makefile:1619: modules] Error 2
make[5]: Leaving directory '/usr/src/linux-headers-5.4.49-rockchip64'
make[4]: *** [Makefile:48: modules-Linux] Error 2
make[4]: Leaving directory '/tmp/zfs-build-root-rdNNDtJ4/BUILD/zfs-kmod-0.8.0/_kmod_build_5.4.49-rockchip64/module'
make[3]: *** [Makefile:871: all-recursive] Error 1
make[3]: Leaving directory '/tmp/zfs-build-root-rdNNDtJ4/BUILD/zfs-kmod-0.8.0/_kmod_build_5.4.49-rockchip64'
make[2]: *** [Makefile:734: all] Error 2
make[2]: Leaving directory '/tmp/zfs-build-root-rdNNDtJ4/BUILD/zfs-kmod-0.8.0/_kmod_build_5.4.49-rockchip64'
error: Bad exit status from /tmp/zfs-build-root-rdNNDtJ4/TMP/rpm-tmp.M7gP99 (%build)


RPM build errors:
    Bad exit status from /tmp/zfs-build-root-rdNNDtJ4/TMP/rpm-tmp.M7gP99 (%build)
make[1]: *** [Makefile:1613: rpm-common] Error 1
make[1]: Leaving directory '/usr/src/zfs'
make: *** [Makefile:1564: rpm-kmod] Error 2
```

**Comment by prometheanfire** [comment] 2020-07-17 15:28
guess there may still be problems with 5.4 then

**Comment by satmandu** [comment] 2020-09-01 17:21
FYI Ubuntu has a workaround for this now: https://git.launchpad.net/ubuntu/+source/zfs-linux/commit/?h=applied/ubuntu/devel&id=e7c101ed4b81cb3c2eda8abba0b50fedac5d6bab

```
diff --git a/module/zfs/vdev_disk.c b/module/zfs/vdev_disk.c
index 8544bb8..2a7096a 100644
--- a/module/zfs/vdev_disk.c
+++ b/module/zfs/vdev_disk.c
@@ -26,6 +26,8 @@
  * Copyright (c) 2012, 2019 by Delphix. All rights reserved.
  */
 
+#include "zfs_compat.h"
+
 #include <sys/zfs_context.h>
 #include <sys/spa_impl.h>
 #include <sys/vdev_disk.h>
diff --git a/module/zfs/zfs_compat.h b/module/zfs/zfs_compat.h
new file mode 100644
index 0000000..6ef26f4
--- /dev/null
+++ b/module/zfs/zfs_compat.h
@@ -0,0 +1,14 @@
+#ifndef _ZFS_COMPAT_H_
+#define _ZFS_COMPAT_H_
+
+/*
+ * preempt_schedule_notrace is GPL-only which breaks the ZFS build, so
+ * replace it with preempt_schedule under the following condition:
+*/
+#if defined(CONFIG_ARM64) && \
+    defined(CONFIG_PREEMPTION) && \
+    defined(CONFIG_BLK_CGROUP)
+#define preempt_schedule_notrace(x) preempt_schedule(x)
+#endif
+
+#endif /* _ZFS_COMPAT_H_ */
```

Also should be noted for: https://github.com/openzfs/zfs/issues/6146 https://github.com/openzfs/zfs/issues/9745 https://github.com/openzfs/zfs/issues/9948 https://github.com/openzfs/zfs/issues/10416

**Comment by neszt** [comment] 2020-09-23 13:25
Aarch64 with kernel 5.8.10 using Armbian on a Rock64

```
MODPOST /var/lib/dkms/zfs/0.8.4/build/module/Module.symvers
FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'preempt_schedule_notrace'
make[4]: *** [scripts/Makefile.modpost:111: /var/lib/dkms/zfs/0.8.4/build/module/Module.symvers] Error 1
make[3]: *** [Makefile:1665: modules] Error 2
make[3]: Leaving directory '/usr/src/linux-headers-5.8.10-rockchip64'
make[2]: *** [Makefile:30: modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/zfs/0.8.4/build/module'
make[1]: *** [Makefile:808: all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/0.8.4/build'
make: *** [Makefile:677: all] Error 2
root@rock64:/# uname -a
Linux rock64 5.8.10-rockchip64 #20.08.3 SMP PREEMPT Fri Sep 18 11:05:12 CEST 2020 aarch64 GNU/Linux
```

**Comment by satmandu** [comment] 2020-09-23 13:28
This [patch from ubuntu ](https://git.launchpad.net/ubuntu/+source/zfs-linux/tree/debian/patches/4700-Fix-DKMS-build-on-arm64-with-PREEMPTION-and-BLK_CGRO.patch)allows zfs 0.8.x to work on arm64 with preempt enabled kernels:

```
From 46cd180400093965271820d34fa1071f9769a0fb Mon Sep 17 00:00:00 2001
From: Juerg Haefliger <juergh@canonical.com>
Date: Tue, 18 Aug 2020 10:52:25 +0200
Subject: [PATCH] Fix DKMS build on arm64 with PREEMPTION and BLK_CGROUP
 enabled

With PREEMPTION=y and BLK_CGROUP=y preempt_schedule_notrace() is being
used on arm64 which is a GPL-only function and hence the build of the
DKMS kernel module fails.

'Fix' that by redefining preempt_schedule_notrace() to preempt_schedule()
which should be safe as long as tracing is not used.

Signed-off-by: Juerg Haefliger <juergh@canonical.com>
---
 module/zfs/vdev_disk.c  |  2 ++
 module/zfs/zfs_compat.h | 14 ++++++++++++++
 2 files changed, 16 insertions(+)
 create mode 100644 module/zfs/zfs_compat.h

diff --git a/module/zfs/vdev_disk.c b/module/zfs/vdev_disk.c
index 8544bb8ffb6f..2a7096a6436d 100644
--- a/module/zfs/vdev_disk.c
+++ b/module/zfs/vdev_disk.c
@@ -26,6 +26,8 @@
  * Copyright (c) 2012, 2019 by Delphix. All rights reserved.
  */
 
+#include "zfs_compat.h"
+
 #include <sys/zfs_context.h>
 #include <sys/spa_impl.h>
 #include <sys/vdev_disk.h>
diff --git a/module/zfs/zfs_compat.h b/module/zfs/zfs_compat.h
new file mode 100644
index 000000000000..6ef26f436f3c
--- /dev/null
+++ b/module/zfs/zfs_compat.h
@@ -0,0 +1,14 @@
+#ifndef _ZFS_COMPAT_H_
+#define _ZFS_COMPAT_H_
+
+/*
+ * preempt_schedule_notrace is GPL-only which breaks the ZFS build, so
+ * replace it with preempt_schedule under the following condition:
+*/
+#if defined(CONFIG_ARM64) && \
+    defined(CONFIG_PREEMPTION) && \
+    defined(CONFIG_BLK_CGROUP)
+#define preempt_schedule_notrace(x) preempt_schedule(x)
+#endif
+
+#endif /* _ZFS_COMPAT_H_ */
-- 
2.25.1
```

**Comment by behlendorf** [comment] 2020-09-23 18:06
I've gone ahead and opened PR #10973 with a version of the patch applied to Ubuntu.  It'd be great if someone could verify this version of the patch resolves the issue.  @satmandu @neszt @grahamc

**Comment by satmandu** [comment] 2020-09-23 19:38
@behlendorf  The patch works for me with the RPI arm64 kernel at https://github.com/Hexxeh/rpi-firmware/commit/a995f0c9a9b3e5dbd2a41f69f5c4c82cdf33c7ec:
```
modprobe configs && zcat /proc/config.gz | grep PREEMPT
# CONFIG_PREEMPT_NONE is not set
# CONFIG_PREEMPT_VOLUNTARY is not set
CONFIG_PREEMPT=y
CONFIG_PREEMPT_COUNT=y
CONFIG_PREEMPTION=y
CONFIG_PREEMPT_RCU=y
CONFIG_PREEMPT_NOTIFIERS=y
CONFIG_DEBUG_PREEMPT=y
CONFIG_PREEMPTIRQ_TRACEPOINTS=y
# CONFIG_PREEMPTIRQ_EVENTS is not set
# CONFIG_PREEMPT_TRACER is not set
# CONFIG_PREEMPTIRQ_DELAY_TEST is not set
satadru@rpi4b ~$ dmesg | grep 'PREEMPT\|ZFS\|taint'
[    0.000000] Linux version 5.4.65-v8+ (dom@buildbot) (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9)) #1341 SMP PREEMPT Tue Sep 15 13:20:32 BST 2020
[    5.396685] spl: loading out-of-tree module taints kernel.
[    5.435122] icp: module license 'CDDL' taints kernel.
[    5.435137] Disabling lock debugging due to kernel taint
[    8.016244] ZFS: Loaded module v2.0.0-rc1, ZFS pool version 5000, ZFS filesystem version 5
satadru@rpi4b ~$ uname -a
Linux rpi4b 5.4.65-v8+ #1341 SMP PREEMPT Tue Sep 15 13:20:32 BST 2020 aarch64 GNU/Linux
```

**Closed** 2020-09-25 20:28 UTC
Labels: Type: Architecture, Type: Building
