### ISSUE TITLE
Fedora 34 repo does not contain latest release version

### ISSUE THREAD

**Issue by amarshall** [openzfs/zfs#12452] opened 2021-08-03 01:25 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| 34
Kernel Version	| 5.13
Architecture	| x86_64
OpenZFS Version	| zfs-2.0.5-1; zfs-kmod-2.0.5-1

### Describe the problem you're observing

Latest release version (ZFS v2.1.0) is not contained in the Fedora 34 (latest Fedora release) ZFS official repository.

### Describe how to reproduce the problem

1. Follow [setup instructions in ZFS documentation](https://openzfs.github.io/openzfs-docs/Getting%20Started/Fedora.html)
2. `dnf info zfs`
3. Expect: latest release (v2.1.0) to be available. Actual: v2.0.5 is latest available

**Comment by tonyhutter** [comment] 2021-08-03 01:49
They're in the `zfs-testing` repo.  Try:
```
sudo dnf install --enablerepo=zfs-testing zfs
```

**Comment by Lalufu** [comment] 2021-08-03 11:46
What's the state of the 2.0 branch? Is it expected to get updates that would allow it to run on newer kernels (like 5.13 that Fedora currently ships)?

**Comment by amarshall** [comment] 2021-08-03 12:18
Forgive me if I’m missing something obvious, but why is it only in the testing repo if it’s not a pre-release and it’s been a month since release?

**Comment by Evernow** [comment] 2021-08-05 00:06
Fedora users can't update due to this, any reason why 2.1.0 isn't in the stable repo?

**Comment by xeghia** [comment] 2021-08-05 11:51
It gives end users a choice. If you want 2.1.0 then enable the test repo, if not, then don't. It's only a label and I don't expect them to maintain more than 2 repos.

Currently 2.0.5 in the stable repo will build for 5.13 although the dependencies are all shot and tied to kernel 5.12, this is what I'm running now though by choice.

Eventually I'm sure they will put 2.1.x in the stable repo but there's no rush, I'm happy to wait for another point release or two.

**Comment by amarshall** [comment] 2021-08-05 13:20
It doesn’t really give much of a choice eventually since 2.0.5 requires kernel < 5.13 (it compiles against it, but this is the spec in the RPM). Nevertheless, your explanation doesn’t indicate why a non-testing release is only in the testing repo. The semantics appear misaligned. There are plenty of other ways to offer multiple versions.

**Comment by Lalufu** [comment] 2021-08-05 13:37
This has always been a bit of a sore point between ZoL and Fedora,
because the latter pretty aggressively rebases to new kernels, and the
release schedule of ZoL was rarely aligned with this. Sometimes ZoL
releases work with kernel versions they don't officially support,
sometimes they don't (2.0.5 seems to work with 5.13). The RPM
requirements are unfortunate, but not really wrong, and you'll be able
to run a 5.13 kernel on Fedora as long as you keep at least one 5.12
kernel installed. This isn't exactly elegant, I admit.

I guess it comes down to a question of manpower, if there aren't enough
knowledgeable people in the project to maintain a major branch like 2.0
against newer kernels while not introducing other changes or bugfixes
then the only time a new kernel gets support is with a bugfix or a new
major branch.

I know I'm not qualified enough to do the work.

**Comment by amarshall** [comment] 2021-08-05 13:55
Sure, and I get that, but it’s not the core issue here because v2.1.0 is a released version which has none of those issues at present. So we come back to, again: *why is a released version only in the testing repo?*.

**Comment by bghira** [comment] 2021-08-05 14:26
it really comes down to not sequestering the builds that are _required_ for Fedora to work with its latest kernel. zfs-testing on Fedora is an oxymoron... that whole distribution is a test ground.

**Comment by tonyhutter** [comment] 2021-08-05 19:54
> Forgive me if I’m missing something obvious, but why is it only in the testing repo if it’s not a pre-release and it’s been a month since release?

I think it's a fair question.  The RPMs were put out while I was on vacation, so I'm sure what the reason was for putting them in testing and not the main repo.  @behlendorf should we promote the zfs-2.1.0 RPMs to the main repo on Fedora?

And to answer some other comments - historically we have put the "newer" releases (like 2.0.x) in the Fedora main repo, while putting the "older" releases (like 0.8.x) in the CentOS main repo, since CentOS users are typically more conservative.  So there is precedent for Fedora getting the latest and greatest release in the main repo.

**Comment by tonyhutter** [comment] 2021-08-06 21:29
I confirmed with @behlendorf, and the zfs-2.1.0 RPMs are now in the main Fedora repo.  Closing issue.

**Closed by tonyhutter** 2021-08-06 21:29 UTC
Labels: Type: Defect

**Comment by gdevenyi** [comment] 2021-08-07 00:30
#10333

**Comment by Evernow** [comment] 2021-08-07 00:32
> 
> 
> #10333

This has nothing to do with Fedora. Why are you commenting this on an Fedora issue report?
