### ISSUE TITLE
zfs send -R fails cannot send more than 65535 snapshots 

### ISSUE THREAD

**Issue by k-u-bux** [openzfs/zfs#6572] opened 2017-08-28 20:26 UTC
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  gentoo
Distribution Version    |  rolling release
Linux Kernel                 |  4.4.6
Architecture                 |  amd64
ZFS Version                  |  0.7.1-r0-gentoo
SPL Version                  | 0.7.1-r0-gentoo

### Describe the problem you're observing
Trying to replicate a zfs dataset with send -R fails for datasets with many snapshots.

I created a list snapshots.home of all snapshots and used binary search to find out how many snapshots I can send. Turns out, the break point is 2^16:

```
zfs send -vR $( awk 'FNR==65536' snapshots.home ) >/dev/null 2>send.log
```
fails with an internal error. Here is the tail of send.log:

```
...
send from @2016-11-27_21-10-01 to backup/home@2016-11-27_21-15-01 estimated size is 1.44M
send from @2016-11-27_21-15-01 to backup/home@2016-11-27_21-20-01 estimated size is 9.77M
total estimated size is 846G
cannot hold: operation not applicable to datasets of this type
internal error: Invalid argument
```
The command
```
zfs send -vR $( awk 'FNR==65535' snapshots.home ) >/dev/null 2>send.log
```
completes just fine.

I conjecture that this is caused by using an unsigned short in the avl data structure:

```
struct avl_node {
        struct avl_node *avl_child[2];  /* left/right children */
        struct avl_node *avl_parent;    /* this node's parent */
        unsigned short avl_child_index; /* my index in parent's avl_child[] */
        short avl_balance;              /* balance value: -1, 0, +1 */
};
```

**Comment by loli10K** [comment] 2017-08-28 20:59
Duplicate https://github.com/zfsonlinux/zfs/issues/5595?

**Comment by mailinglists35** [comment] 2017-08-30 13:52
I think maybe this is the cause of 5595, so perhaps it's better to mark 5595 as a duplicate of this

**Comment by TerraTech** [comment] 2019-01-14 15:13
We have had to work around this snapshot issue for awhile now, by chunking up the work.  Any chance of a fix making it into the v0.8.x release?  If the issue is an 'unsigned short', what are the ramifications of bumping that up to a ```size_t```?

**Comment by TerraTech** [comment] 2019-01-18 06:41
FWIW, I just hit this again today, sending a server's replication stream package that has **43,140** snapshots.

Actually, after looking at this some more, the 'unsigned short' doesn't seem to be the problem because it is simply the L/R index in the AVL tree (learned a new data structure day).

Does anyone know what the maximum number of holds ```lzc_hold()``` (via: _lib/libzfs_core/libzfs_core.c_) that can be done?  Seems the error occurs after ```lzc_ioctl()``` is called into the kernel.

**Comment by ser** [comment] 2020-02-17 01:41
I met this problem in a small home server, are you sure it can't be fixed?

**Comment by freqlabs** [comment] 2020-08-08 02:31
I can reproduce this on FreeBSD as well. A user reported this error trying to send ~1000 snapshots on a somewhat fleshed out hierarchy, and I can produce the same error message trying to incremental send an empty dataset with ~10000 snapshots.

**Comment by hmblprogrammer** [comment] 2021-02-15 14:46
I am *not* a kernel developer, but I don't understand how [the commit @behlendorf made](https://github.com/openzfs/zfs/commit/009cc8e884a84aeebed612ab64c30f77eab38392) will resolve this under Linux: If I understand correctly, `zc_nvlist_src_size` is now tunable but it will now default to the `KMALLOC_MAX_SIZE` under Linux where it was hard-coded to that before.

It can't be raised above `KMALLOC_MAX_SIZE` because then the call to `kmem_alloc(nvsize` will fail because it's requesting more memory than `kmem_alloc` will provide... right?

Does it need to use `vmem_alloc` if `zc_nvlist_src_size> KMALLOC_MAX_SIZE`? Is that even possible? This is a bit beyond my depth, but I know trying to `zfs send` a dataset with 44,540 snapshots fails...

**Comment by behlendorf** [comment] 2021-02-15 20:18
> It can't be raised above KMALLOC_MAX_SIZE because then the call to kmem_alloc(nvsize will fail because it's requesting more memory than kmem_alloc will provide... right?

It does default to `KMALLOC_MAX_SIZE ` but internally it's using `vmem_alloc()` so you can perform larger allocations.  It's probably reasonable to even increase that default size, but we do want to keep a reasonable limit on it.

If you set the limit larger with the module options, say to 1M, are you able to send all of the snapshots?

**Comment by mailinglists35** [comment] 2021-02-15 21:59
> > It can't be raised above KMALLOC_MAX_SIZE because then the call to kmem_alloc(nvsize will fail because it's requesting more memory than kmem_alloc will provide... right?
> 
> 
> 
> It does default to `KMALLOC_MAX_SIZE ` but internally it's using `vmem_alloc()` so you can perform larger allocations.  It's probably reasonable to even increase that default size, but we do want to keep a reasonable limit on it.
> 
> 
> 
> If you set the limit larger with the module options, say to 1M, are you able to send all of the snapshots?

do you mean in order to send more than 65535 snapshots, I must adjust zc_nvlist_src_size to 1M? what is the relation between zc_nvlist_src_size and the maximum number of snapshots? what should I tune zc_nvlist_src_size to in order to send millions of snapshots, for example?

**Comment by hmblprogrammer** [comment] 2021-02-15 23:20
> internally it's using vmem_alloc() so you can perform larger allocations

Perfect. That was where my disconnect was -- I couldn't tell if it was using `vmem_alloc` or `kmem_alloc`

> If you set the limit larger with the module options, say to 1M, are you able to send all of the snapshots?

I'll do a test. I have an older version of the module right now so I need to upgrade (and maybe build from source, because I'm using proxmox...)

**Comment by freqlabs** [comment] 2021-02-17 17:12
How big the nvlist will be depends on the size of the actual names of the datasets and snapshots, plus a bit of nvlist overhead.

**Comment by behlendorf** [comment] 2021-02-17 17:22
> what should I tune zc_nvlist_src_size to in order to send millions of snapshots, for example?

As @freqlabs mentioned you can roughly approximate the memory requirement as the `number-of-snapshots-and-datasets * average-name-length`.  So for a million snapshots with say an average name length of 20 characters, you'd need to set it to about 20M.  Since we are using `vmalloc` here, I think it'd be fine to increase the default on Linux to say 1M or even 4M but I think we do want to keep it reasonably bounded.

**Comment by IsaacVaughn** [comment] 2021-02-20 13:18
Even with a larger default, this seems confusing for any users who do exceed the larger default limit. Would it be possible to propagate the exact error up to the user facing tooling instead of just reporting "internal error"?
e.g. "Error: Operation would exceed maximum memory allocation, set zc_nvlist_src_size=XXX to proceed."

**Comment by behlendorf** [comment] 2021-02-23 02:18
I've opened PR #11638 which increases the size considerably, up to 128MB.  This change does not improve the error message but should make this much less likely to hit.

**Closed** 2021-02-24 17:57 UTC
Labels: Component: Send/Recv, Type: Defect
