### ISSUE TITLE
error compiling on centos 7 dkms kernel 5.8+

### ISSUE THREAD

**Issue by xgiovio** [openzfs/zfs#11035] opened 2020-10-09 01:45 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| centos
Distribution Version	| 7
Linux Kernel	| 5.8
Architecture	| x86
ZFS Version	| 0.8.5
SPL Version	|

### Describe the problem you're observing
error in compiling using dkms install zfs-0.8.5

### Describe how to reproduce the problem
compiling zfs for current kernel

**Comment by behlendorf** [comment] 2020-10-09 17:16
You'll need to include the exact build failure from the dkms logs for this to be investigated.

**Comment by xgiovio** [comment] 2020-11-04 22:04
I discovered the problem. From kernel 5.8 the default version of gcc in centos7 is unable to compile code against the kernel. It needs a newer version of gcc.

I resolved installas a software collection devtools-8
and doing a symlink og the new gcc to /bin/gcc

Maybe this should be mentioned in some docs

**Comment by behlendorf** [comment] 2020-11-05 20:54
I assume this was for the elrepo kernel-ml kernel?  It looks like this particular problem was mentioned in the [release announcement](http://lists.elrepo.org/pipermail/elrepo/2020-August/005347.html).  It'd be reasonable to add a brief comment to the installation [documentation for CentOS 7](https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL%20and%20CentOS.html).

**Comment by xgiovio** [comment] 2020-11-06 00:16
yes kernel-ml kernel on centos7. i don't know if I have to close this issue or you would like to have  it opened while you decide what to do.

**Comment by behlendorf** [comment] 2020-11-06 00:59
@xgiovio let's close it out.  Thanks for following up with the root cause.

**Closed by behlendorf** 2020-11-06 00:59 UTC
Labels: Type: Building, Type: Documentation
