### ISSUE TITLE
BUG: kernel NULL pointer dereference, address: 0000000000000020

### ISSUE THREAD

**Issue by reactormonk** [openzfs/zfs#11402] opened 2020-12-25 09:44 UTC
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Archlinux
Distribution Version	| 2.0.0_5.9.14.arch1.1-1
Linux Kernel	| 5.9.14.arch1.1
Architecture	| x86_64
ZFS Version	| 2.0.0
SPL Version	| 2.0.0

### Describe the problem you're observing

zfs module crash

### Describe how to reproduce the problem

Put some load on the system, use an l2arc SSD.

### Include any warning/errors/backtraces from the system logs

```
[92344.117725] BUG: kernel NULL pointer dereference, address: 0000000000000020
[92344.117731] #PF: supervisor read access in kernel mode
[92344.117733] #PF: error_code(0x0000) - not-present page
[92344.117740] PGD 7c66cb067 P4D 7c66cb067 PUD 0 
[92344.117748] Oops: 0000 [#1] PREEMPT SMP NOPTI
[92344.117752] CPU: 9 PID: 813 Comm: l2arc_feed Tainted: P        W  OE     5.9.14-arch1-1 #1
[92344.117755] Hardware name: System manufacturer System Product Name/PRIME B350-PLUS, BIOS 5407 12/31/2019
[92344.117821] RIP: 0010:buf_hash_remove+0x3d/0x90 [zfs]
[92344.117825] Code: 33 48 8b 7f 30 e8 c3 b5 f3 fe 48 23 05 7c e4 26 00 48 89 c1 48 8b 05 7a e4 26 00 48 8d 14 c8 48 8b 02 48 39 c3 74 10 48 89 c2 <48> 8b 40 20 48 39 c3 75 f4 48 83 c2 20 48 8b 43 20 48 89 02 48 c7
[92344.117828] RSP: 0018:ffffb3a5814d7ce8 EFLAGS: 00010282
[92344.117831] RAX: 0000000000000000 RBX: ffff9aa723f71d80 RCX: 000000000010e544
[92344.117834] RDX: 0000000000000000 RSI: 00000000000000d0 RDI: 2c50b589eb685976
[92344.117836] RBP: ffffffffc20a2be0 R08: 9ae16a3b2f90408f R09: 9ae16a3b2f90404f
[92344.117838] R10: ffff9aa723f71360 R11: 0000000000000000 R12: ffffffffc20a2aa0
[92344.117840] R13: 0000000000000000 R14: 0000000000000001 R15: 0000000000000000
[92344.117843] FS:  0000000000000000(0000) GS:ffff9aa77ea40000(0000) knlGS:0000000000000000
[92344.117844] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[92344.117846] CR2: 0000000000000020 CR3: 00000004d22d0000 CR4: 00000000003506e0
[92344.117848] Call Trace:
[92344.117901]  arc_change_state.constprop.0+0x2cd/0x4c0 [zfs]
[92344.117953]  l2arc_evict+0x3c3/0x580 [zfs]
[92344.118005]  l2arc_feed_thread+0x468/0x1ae0 [zfs]
[92344.118009]  ? update_curr+0x108/0x1f0
[92344.118061]  ? l2arc_remove_vdev+0x200/0x200 [zfs]
[92344.118068]  ? __thread_exit+0x20/0x20 [spl]
[92344.118075]  thread_generic_wrapper+0x6f/0x80 [spl]
[92344.118079]  kthread+0x142/0x160
[92344.118082]  ? __kthread_bind_mask+0x60/0x60
[92344.118086]  ret_from_fork+0x22/0x30
[92344.118089] Modules linked in: rfcomm nfnetlink cmac algif_hash algif_skcipher af_alg bnep ext4 mbcache jbd2 dm_crypt cbc encrypted_keys trusted tpm loop zfs(POE) xpad ff_memless uvcvideo zunicode(POE) videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 zzstd(OE) videobuf2_common snd
_usb_audio videodev btusb snd_usbmidi_lib snd_rawmidi btrtl btbcm snd_seq_device btintel eeepc_wmi mc zlua(OE) asus_wmi vboxnetflt(OE) bluetooth vboxnetadp(OE) battery zavl(POE) ecdh_generic sparse_keymap icp(POE) hid_lenovo rfkill wmi_bmof ecc vboxdrv(OE) crc16 amdgpu edac_mce_amd snd_hda_codec_realtek nls_iso8859_1 snd_hda_codec_generic kvm_amd nls_cp437 ledtrig_audio snd_hda_codec_hdmi vfat fat zcommon(POE) snd_hda_intel kvm snd_intel_dspcfg snd_hda_codec gpu_sched znvpair(POE) i2c_algo_bit snd_hda_core ttm irqbypass snd_hwdep crct10dif_pclmul crc32_pclmul ghash_clmulni_intel drm_kms_helper spl(OE) aesni_intel snd_pcm r8169 joydev cec realtek crypto_simd rc_core snd_timer cryptd mdio_devres ccp glue_helper
[92344.118127]  of_mdio mousedev snd fixed_phy syscopyarea sysfillrect input_leds sp5100_tco sysimgblt rapl pcspkr soundcore fb_sys_fops k10temp libphy i2c_piix4 rng_core wmi gpio_amdpt pinctrl_amd evdev mac_hid acpi_cpufreq dm_mod drm usbip_host usbip_core crypto_user fuse agpgart ip_tables x_tables hid_steam btrfs blake2b_generic libcrc32c crc32c_generic xor hid_generic usbhid hid raid6_pq crc32c_intel xhci_pci xhci_pci_renesas xhci_hcd
[92344.118148] CR2: 0000000000000020
[92344.118151] ---[ end trace 6c9692e874d6b4f1 ]---
[92344.118200] RIP: 0010:buf_hash_remove+0x3d/0x90 [zfs]
[92344.118202] Code: 33 48 8b 7f 30 e8 c3 b5 f3 fe 48 23 05 7c e4 26 00 48 89 c1 48 8b 05 7a e4 26 00 48 8d 14 c8 48 8b 02 48 39 c3 74 10 48 89 c2 <48> 8b 40 20 48 39 c3 75 f4 48 83 c2 20 48 8b 43 20 48 89 02 48 c7
[92344.118204] RSP: 0018:ffffb3a5814d7ce8 EFLAGS: 00010282
[92344.118206] RAX: 0000000000000000 RBX: ffff9aa723f71d80 RCX: 000000000010e544
[92344.118208] RDX: 0000000000000000 RSI: 00000000000000d0 RDI: 2c50b589eb685976
[92344.118209] RBP: ffffffffc20a2be0 R08: 9ae16a3b2f90408f R09: 9ae16a3b2f90404f
[92344.118210] R10: ffff9aa723f71360 R11: 0000000000000000 R12: ffffffffc20a2aa0
[92344.118211] R13: 0000000000000000 R14: 0000000000000001 R15: 0000000000000000
[92344.118213] FS:  0000000000000000(0000) GS:ffff9aa77ea40000(0000) knlGS:0000000000000000
[92344.118214] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[92344.118216] CR2: 0000000000000020 CR3: 00000004d22d0000 CR4: 00000000003506e0
```

**Comment by behlendorf** [comment] 2020-12-28 20:09
Duplicate of #11338.

**Closed by behlendorf** 2020-12-28 20:09 UTC
Labels: Type: Defect
