### ISSUE TITLE
Linux 5.8 Kernel oops during pyzfs_unittest

### ISSUE THREAD

**Issue by aerusso** [openzfs/zfs#10955] opened 2020-09-20 13:10 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| unstable
Linux Kernel	| 5.8
Architecture	| amd64
ZFS Version	| 0.8.5-staging (up to and including 4fc1b3c4d)

### Describe the problem you're observing
Running the `pyzfs_unittest` causes a kernel oops.

### Describe how to reproduce the problem
as above (either Debian testing 5.8.0-1 or unstable 5.8.0-2)

### Include any warning/errors/backtraces from the system logs
```
Sep 20 06:47:12 REDACTED kernel: ------------[ cut here ]------------
Sep 20 06:47:12 REDACTED kernel: WARNING: CPU: 0 PID: 2534 at fs/read_write.c:542 __kernel_write+0x139/0x160
Sep 20 06:47:12 REDACTED kernel: Modules linked in: loop rfcomm ctr ccm cmac algif_hash algif_skcipher af_alg bnep binfmt_misc zfs(POE) zunicode(POE) zlua(POE) zavl(POE) icp(POE) zcommon(POE) znvpair(POE) spl(OE) joydev btusb btrtl btbcm btintel bluetooth uvcvideo videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 videobuf2_common jitterentropy_rng videodev drbg ansi_cprng ecdh_generic mc ecc intel_rapl_msr intel_rapl_common snd_hda_codec_hdmi snd_hda_codec_realtek snd_hda_codec_generic ledtrig_audio iwldvm snd_hda_intel iTCO_wdt intel_pmc_bxt snd_intel_dspcfg x86_pkg_temp_thermal iTCO_vendor_support intel_powerclamp mac80211 at24 libarc4 watchdog snd_hda_codec coretemp efi_pstore iwlwifi snd_hda_core snd_hwdep rapl intel_cstate snd_pcm efivars intel_uncore cfg80211 snd_timer jmb38x_ms psmouse snd i2c_i801 mei_me alx pcspkr i2c_smbus sg lpc_ich mei soundcore memstick mdio ideapad_laptop sparse_keymap rfkill wmi evdev ac button nft_counter nft_ct nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c nls_ascii
Sep 20 06:47:12 REDACTED kernel:  nls_cp437 vfat fat nfsd auth_rpcgss nf_tables nfs_acl lockd grace nfnetlink sunrpc ip_tables x_tables ext4 crc16 mbcache jbd2 crc32c_generic sr_mod sd_mod cdrom t10_pi crc_t10dif crct10dif_generic i915 crct10dif_pclmul crct10dif_common crc32_pclmul crc32c_intel ghash_clmulni_intel i2c_algo_bit xhci_pci drm_kms_helper xhci_hcd ahci serio_raw libahci ehci_pci aesni_intel cec libata glue_helper ehci_hcd libaes crypto_simd drm sdhci_pci scsi_mod cqhci sdhci cryptd usbcore mmc_core usb_common battery video efivarfs autofs4
Sep 20 06:47:12 REDACTED kernel: CPU: 0 PID: 2534 Comm: python3.8 Tainted: P           OE     5.8.0-1-amd64 #1 Debian 5.8.7-1
Sep 20 06:47:12 REDACTED kernel: Hardware name: LENOVO Lenovo IdeaPad Y480/Product Name, BIOS 5DCN36WW(V2.03) 05/03/2012
Sep 20 06:47:12 REDACTED kernel: RIP: 0010:__kernel_write+0x139/0x160
Sep 20 06:47:12 REDACTED kernel: Code: 4c 89 c6 e8 d9 c3 ff ff 49 89 c4 e9 56 ff ff ff 45 31 c9 45 31 c0 b9 01 00 00 00 4c 89 f2 89 ee 4c 89 ef e8 49 e1 04 00 eb b2 <0f> 0b 49 c7 c4 f7 ff ff ff 5b 5d 4c 89 e0 41 5c 41 5d 41 5e c3 49
Sep 20 06:47:12 REDACTED kernel: RSP: 0018:ffffb020c1c7b970 EFLAGS: 00010246
Sep 20 06:47:12 REDACTED kernel: RAX: 00000000080a801d RBX: ffff9ef1ff743900 RCX: ffffb020c1c7b9d0
Sep 20 06:47:12 REDACTED kernel: RDX: 0000000000000138 RSI: ffff9ef25d2e2000 RDI: ffff9ef1ff743900
Sep 20 06:47:12 REDACTED kernel: RBP: ffff9ef25d2e2000 R08: 0000000000000000 R09: ffff9ef229355080
Sep 20 06:47:12 REDACTED kernel: R10: ffff9ef1db296540 R11: 0000000000000001 R12: 0000000000000138
Sep 20 06:47:12 REDACTED kernel: R13: ffffb020c1c7b9d0 R14: ffff9ef22989cc40 R15: ffffb020c1c7bb00
Sep 20 06:47:12 REDACTED kernel: FS:  00007feb5c933740(0000) GS:ffff9ef277200000(0000) knlGS:0000000000000000
Sep 20 06:47:12 REDACTED kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Sep 20 06:47:12 REDACTED kernel: CR2: 00007feb5bade640 CR3: 000000019be1c003 CR4: 00000000001606f0
Sep 20 06:47:12 REDACTED kernel: Call Trace:
Sep 20 06:47:12 REDACTED kernel:  kernel_write+0x62/0xb0
Sep 20 06:47:12 REDACTED kernel:  ? kfree+0xb3/0x230
Sep 20 06:47:12 REDACTED kernel:  vn_rdwr+0x57/0xc0 [spl]
Sep 20 06:47:12 REDACTED kernel:  dump_bytes_cb+0x73/0xf0 [zfs]
Sep 20 06:47:12 REDACTED kernel:  dump_record+0x92/0x180 [zfs]
Sep 20 06:47:12 REDACTED kernel:  dmu_send_impl+0x4ef/0xb50 [zfs]
Sep 20 06:47:12 REDACTED kernel:  ? mutex_lock+0xe/0x30
Sep 20 06:47:12 REDACTED kernel:  dmu_send+0x344/0x440 [zfs]
Sep 20 06:47:12 REDACTED kernel:  zfs_ioc_send_new+0x125/0x1b0 [zfs]
Sep 20 06:47:12 REDACTED kernel:  zfsdev_ioctl+0x1e2/0x900 [zfs]
Sep 20 06:47:12 REDACTED kernel:  ksys_ioctl+0x82/0xc0
Sep 20 06:47:12 REDACTED kernel:  __x64_sys_ioctl+0x16/0x20
Sep 20 06:47:12 REDACTED kernel:  do_syscall_64+0x4d/0xc0
Sep 20 06:47:12 REDACTED kernel:  entry_SYSCALL_64_after_hwframe+0x44/0xa9
Sep 20 06:47:12 REDACTED kernel: RIP: 0033:0x7feb5ca2ad87
Sep 20 06:47:12 REDACTED kernel: Code: 00 00 00 48 8b 05 09 91 0c 00 64 c7 00 26 00 00 00 48 c7 c0 ff ff ff ff c3 66 2e 0f 1f 84 00 00 00 00 00 b8 10 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d d9 90 0c 00 f7 d8 64 89 01 48
Sep 20 06:47:12 REDACTED kernel: RSP: 002b:00007fffe1b10368 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
Sep 20 06:47:12 REDACTED kernel: RAX: ffffffffffffffda RBX: 0000000000000000 RCX: 00007feb5ca2ad87
Sep 20 06:47:12 REDACTED kernel: RDX: 00007fffe1b10390 RSI: 0000000000005a40 RDI: 0000000000000003
Sep 20 06:47:12 REDACTED kernel: RBP: 00007fffe1b13970 R08: 0000000000000005 R09: 0000000000e4bc00
Sep 20 06:47:12 REDACTED kernel: R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000005a40
Sep 20 06:47:12 REDACTED kernel: R13: 00007fffe1b10390 R14: 0000000000000003 R15: 0000000000005a40
Sep 20 06:47:12 REDACTED kernel: ---[ end trace 0cedec842a33ce32 ]---
```

This coincides with `test_send_to_broken_pipe_2` when running the pyzfs test.  It does not directly lead to a test failure.

**Comment by tonyhutter** [comment] 2020-09-21 15:45
This bug is in master as well: https://github.com/openzfs/zfs/issues/10940  Closing as a dupe of that bug.

**Closed by tonyhutter** 2020-09-21 15:45 UTC
Labels: Status: Triage Needed, Type: Defect
