### ISSUE TITLE
zpool wait hangs indefinitely on ARM

### ISSUE THREAD

**Issue by arm32let** [openzfs/zfs#11424] opened 2021-01-02 14:11 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| debian
Distribution Version	| 9
Linux Kernel	| 4.9.80
Architecture	| armv7
ZFS Version	| 2.0.0

### Describe the problem you're observing

`zpool wait -t remove` hangs indefinitely. Found by running the test suite.

### Describe how to reproduce the problem

`zpool wait -t remove $RANDOM`.

**Comment by ahrens** [comment] 2021-01-04 18:49
@jgallag88 Could you take a look at this or see what additional data we would need to gather to diagnose it?  Maybe this is specific to armv7??

**Comment by jgallag88** [comment] 2021-01-05 06:35
I've reproduced this on ARMv7 using qemu. The problem is in this code (from `zpool_main.c`):
```
int
zpool_do_wait(int argc, char **argv)
{
...
	char c;
...
	while ((c = getopt(argc, argv, "HpT:t:")) != -1) {
...
```
ARMv7 is one of the platforms where `char` is an `unsigned char` instead of a `signed char`. Because `c` is unsigned, it never equals `-1`, and so the program loops here forever.

**Comment by jgallag88** [comment] 2021-01-05 06:49
This was fixed a few days ago in https://github.com/openzfs/zfs/pull/11359. I tested with that change on ARMv7 and confirmed the fix worked as expected. I see that change is already in the `zfs-2.0.1-staging` branch, so it looks like this should be resolved in the next minor release.

**Closed** 2021-01-05 19:21 UTC
Labels: Status: Triage Needed, Type: Defect
