### ISSUE TITLE
HEAD issues mounting encrypted datasets/corrupting metadata

### ISSUE THREAD

**Issue by 65a** [openzfs/zfs#11294] opened 2020-12-06 07:53 UTC
### System information

Type | HEAD/Linux 5.9
 --- | ---
Distribution Name	| Arch-ish
Distribution Version	| n/a
Linux Kernel	| 5.9.1
Architecture	| x86_64
ZFS Version	| 2.0.0-248_gd1d47691c
SPL Version	| 2.0.0-248_gd1d47691c

### Describe the problem you're observing

Encrypted datasets failed to mount. Permanent errors were logged on the pool:
status: One or more devices has experienced an error resulting in data
        corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
        entire pool from backup.

The erroneous files were the "<0x0>" metadata files for each encrypted mountpoint

zfs mount -a returned "Input/Output error" for each mountpoint.

### Describe how to reproduce the problem

Create a pool (possibly using encrypted send/recv) a few years ago with encrypted mountpoints, use HEAD variants of spl and zfs. Attempt to mount encrypted mountpoints.

### Include any warning/errors/backtraces from the system logs

I was able to resolve the data access issue (but not the permanent pool error log) by reverting to 2.0.0-150_g3928ec533, which successfully mounts the encrypted datasets. Scrub under both versions returns no errors or checksum problems.

**Comment by 65a** [comment] 2020-12-06 07:54
I have a build with d1d47691c256cd7e15af7819ea33024e6693e9c5 reverted, I will try that tomorrow after a full pool backup.

**Comment by gamanakis** [comment] 2020-12-06 12:07
I am the author of that d1d4769.
Which version of ZFS had you created the encrypted dataset with?

**Comment by gamanakis** [comment] 2020-12-06 12:08
CC: @tcaputi @behlendorf

**Comment by 65a** [comment] 2020-12-06 16:51
I haven't actually bisected it to that commit yet, but that commit seemed relevant given the nature of the problem. I *think* I saw a segfault and some bizarre output during zfs load-key when I first brought up the affected version, but there was nothing in dmesg. Once I've backed up on the working version, I'll bring it up on the other two versions and see if I can get any more detail out of it.

Re: pool/dataset age: I'm not actually sure, the pool's disks are from approximately October 2019 (was running HEAD then as well), but the datasets may predate that. Definitely not that recent.

**Comment by gamanakis** [comment] 2020-12-06 19:00
I am interested to know if d1d4769 is the one to blame. I did test with encrypted datasets created with 0.8.5 and have them raw-sent to d1d4769 as well as locally mounted by d1d4769 but did not see any problems.

**Comment by 65a** [comment] 2020-12-06 20:09
Backup is running now. I thought I had built a machine image with that commit reverted, but evidently I failed because the revision matched the failing version, I'll try again after backup completes. I can confirm that rolling forward to 2.0.0-248_gd1d47691c reproduces for me, and rolling back to 2.0.0-150_g3928ec533 fixes. If it's useful, the failing mounts aren't the encrypted dataset proper, but the encrypted (same key, inherited) sub-datasets under that. I don't see errors for the metadata for the top level dataset, only its children. 

The dataset was created 2019-10-11, so it would have been created with HEAD zfs around that time, I usually update at least monthly.

**Comment by gamanakis** [comment] 2020-12-06 22:02
I see what you mean regarding encrypted children. Just tested with 0.8.5 and d1d4769, raw sends and local mounting work as expected. Could you provide a script that reproduces the faulty behaviour?

**Comment by 65a** [comment] 2020-12-07 02:25
I can confirm reverting d1d47691c256cd7e15af7819ea33024e6693e9c5 does allow me to mount the pool. I'm not sure how to make this a test case, or why mounting the pool is failing unfortunately :(

**Comment by 65a** [comment] 2020-12-07 02:28
Is it possible my metadata is in a state that invalidates the assumptions in the commit? I've been running bleeding edge commits for about a year on the pool.

**Comment by gamanakis** [comment] 2020-12-07 06:59
It seems you are running some intermediate version of encryption that existed in master between releases which is causing the problem with that commit, and is not covered by Errata3 in ZTS. I will take another look to see how we can resolve it.

**Comment by gamanakis** [comment] 2020-12-07 11:34
I believe I found a way around this, in `spa_do_crypt_objset_mac_abd()` we could skip comparing the `local_mac` if `OBJSET_FLAG_USERACCOUNTING_COMPLETE` and `OBJSET_FLAG_USEROBJACCOUNTING_COMPLETE` are not set. This also resolves Errata3 in ZTS without having to check the key version.

**Comment by 65a** [comment] 2021-02-01 19:33
Any update here? I am still having to revert the patchset, I have various pools created at different times that have been affected. I'm also interested in understanding how I can clear the error log on my pools without recreating them.

**Comment by gamanakis** [comment] 2021-02-07 17:18
I am still working on #11300 which will resolve this issue. Could you post an example of the error you would like to clear?

**Comment by woodypl** [comment] 2021-03-14 14:16
I am also affected by this. The error in question appears when running `zpool status -v` and looks like this:

```
errors: Permanent errors have been detected in the following files:

        pool/volume:<0x0>
```

**Comment by jjlawren** [comment] 2021-05-03 22:23
I've run into this issue on a zpool originally created on SmartOS/Illumos. When I attempt to mount/load-key any encrypted datasets in the pool, it results in the behavior from the original description. Would this have a similar root cause?

**Comment by lundman** [comment] 2021-05-03 23:06
We had to deal with the over in macOS, as we added crypto first, then userobj/project quotas, just like illumOS. 

https://github.com/openzfsonosx/openzfs/commit/38410165070d2ed1e1cf8bbb19e22ddf151ee7f9

we re-test the MAC with the old style and if that works, pass it. A scrub will then fix everything.. however, a proper solution should perhaps be sought?

**Comment by gamanakis** [comment] 2021-05-11 05:56
This seems to be specific on when the dataset was created. Reverting commit
d1d4769 should make the dataset mountable again and scrubbing twice should
clear any errors reported by zpool status.

>

**Comment by jjlawren** [comment] 2021-05-21 16:47
> This seems to be specific on when the dataset was created.

As a test I imported the existing pool where this is an issue into a recent version of SmartOS. I then created a new encrypted child dataset on the pool. Still cannot mount it when booting back into a 2.0.4 system, throws the same error. I suppose I'll wait for a release with the recently merged revert.

**Comment by gamanakis** [comment] 2021-05-21 18:40
In current master d1d4769 is reverted. Let me know if you have an encrypted dataset (with data you would like to salvage) that is not mounting with current master or 2.0.4 in Linux. I could try to come up with a patch to at least get you your data back.

**Comment by jjlawren** [comment] 2021-05-21 20:08
I'd need to look into how to replace the package I'm currently using with a local build, but I'd be interested in a 2.0.4 patch.

**Comment by gamanakis** [comment] 2021-05-21 22:30
Here is a work-around that bypasses comparing the local_mac which presumably causes the mount to fail and the errors in zpool status.
```
diff --git a/module/zfs/dsl_crypt.c b/module/zfs/dsl_crypt.c
index 26d4c2fe7..35da63ffc 100644
--- a/module/zfs/dsl_crypt.c
+++ b/module/zfs/dsl_crypt.c
@@ -2701,8 +2701,7 @@ spa_do_crypt_objset_mac_abd(boolean_t generate, spa_t *spa, uint64_t dsobj,
                return (0);
        }
 
-       if (bcmp(portable_mac, osp->os_portable_mac, ZIO_OBJSET_MAC_LEN) != 0 ||
-           bcmp(local_mac, osp->os_local_mac, ZIO_OBJSET_MAC_LEN) != 0) {
+       if (bcmp(portable_mac, osp->os_portable_mac, ZIO_OBJSET_MAC_LEN) != 0) {
                abd_return_buf(abd, buf, datalen);
                return (SET_ERROR(ECKSUM));
        }
```

**Comment by jjlawren** [comment] 2021-05-22 05:43
@gamanakis thanks! I was able to apply the patch to the 2.0.4 release, build, and load the datasets without issue. 👍

**Comment by tsjk** [comment] 2021-06-07 16:01
I've stumbled upon this as well, on a system where the entire pool is encrypted (usually I don't set it up like that anymore). That system has also ran zfs encrryption for a longer time, and it make sense that there could be some master key compatibility issue. This has not occurred on other systems I have zfs encryption on, which have been converted from cryptsetup + zfs to zfs w/ encryption more recently. I run v2.1.0rc6 with Linux v5.12.8 (actually pf-kernel patchset v5.12_p4)
I'm going to try to apply the revert, and recompile my kernel (I have zfs built-in), and see if my datasets can be mounted.

**Comment by tsjk** [comment] 2021-06-08 05:09
Applying https://github.com/behlendorf/zfs/commit/faa5673982a5d9768c5b0f8ba76c38ad9c6d01e8.patch enabled me to mount the datasets in question.

**Closed** 2022-01-21 19:41 UTC
Labels: Type: Defect, Status: Triage Needed
