### ISSUE TITLE
Can't enable userquota on dataset sent to encrypted root

### ISSUE THREAD

**Issue by floriplum** [openzfs/zfs#9501] opened 2019-10-23 15:24 UTC
## System information
Type | Version/Name
 --- | --- 
Distribution Name	| Debian stable
Distribution Version	| Debian Buster
Linux Kernel	| 4.19.0-6-amd64
Architecture	| x86_64
ZFS Version	| 0.8.2-2
SPL Version	| 0.8.2-2

### Describe the problem you're observing
When i try to enable userquota on a dataset i sent to an encrypted root the userquota is not set. If i now try to see the usage with "zfs userspace" i get an error message.
If i create a new dataset below the new encryption root i can set the userquota just fine.

### Describe how to reproduce the problem
Create a new encryption root and send an unencrypted dataset to a dataset below the new encryption root. Now try to set a userquota for the new dataset. Now try to get the quota used with "zfs userspace".

### Include any warning/errors/backtraces from the system logs
```sudo zfs userspace tank/encryption-root/backup 
cannot get used/quota for tank/encryption-root/backup: unsupported version or feature```

**Comment by behlendorf** [comment] 2019-10-28 21:53
Can you verify that mounting the encrypted datasets resolves the issue?  Since the quota information is not included in the send stream it's necessary to calculate this after it's received.  This operation will be trigger when the dataset is first mounted.

**Comment by floriplum** [comment] 2019-10-28 23:28
I just tried mounting the encrypted dataset but i still can't set the userquota. But i can set the normal quota just fine.
Are there any logs i could provide that would be helpful?

**Comment by behlendorf** [comment] 2019-10-28 23:37
Can you double check that the feature is enabled on your pool:

```
$ zpool get feature@userobj_accounting
NAME  PROPERTY                    VALUE                       SOURCE
tank  feature@userobj_accounting  active                      local
```

**Comment by floriplum** [comment] 2019-10-29 00:06
Yes the output basically looks the same.
And for new datasets in the same pool  the userquota is working, it is just not working on the datasets created by zfs receive.

**Comment by loli10K** [comment] 2019-10-29 18:26
The issue seems to be caused by the following lines:
https://github.com/zfsonlinux/zfs/blob/1222e921c9e3d8f5c693f196435be4604a1187c0/module/zfs/dmu_objset.c#L1069-L1075

`zfs_userspace_many()` is returing `ENOTSUP` becase `dmu_objset_userspace_present()` is false.

```
Thread 242 hit Breakpoint 1, zfs_userspace_many (zfsvfs=0xffff88020e520000, type=ZFS_PROP_USERUSED, cookiep=0xffff88023174b148, vbuf=0xffff880232b30000, bufsizep=0xffff880231749018)
    at /usr/src/zfs/module/zfs/../os/linux/zfs/zfs_vfsops.c:737
737	{
(gdb) list
732	}
733	
734	int
735	zfs_userspace_many(zfsvfs_t *zfsvfs, zfs_userquota_prop_t type,
736	    uint64_t *cookiep, void *vbuf, uint64_t *bufsizep)
737	{
738		int error;
739		zap_cursor_t zc;
740		zap_attribute_t za;
741		zfs_useracct_t *buf = vbuf;
(gdb) 
742		uint64_t obj;
743		int offset = 0;
744	
745		if (!dmu_objset_userspace_present(zfsvfs->z_os))
746			return (SET_ERROR(ENOTSUP));
747	
748		if ((type == ZFS_PROP_PROJECTQUOTA || type == ZFS_PROP_PROJECTUSED ||
749		    type == ZFS_PROP_PROJECTOBJQUOTA ||
750		    type == ZFS_PROP_PROJECTOBJUSED) &&
751		    !dmu_objset_projectquota_present(zfsvfs->z_os))
(gdb) p/t zfsvfs->z_os->os_flags 
$1 = 110
(gdb) up
#1  0xffffffffc0805b3b in zfs_ioc_userspace_many (zc=0xffff880231748000) at /usr/src/zfs/module/zfs/zfs_ioctl.c:5742
5742		error = zfs_userspace_many(zfsvfs, zc->zc_objset_type, &zc->zc_cookie,
(gdb) p zc->zc_name
$2 = "testpool1/recv/fs", '\000' <repeats 4078 times>
(gdb) fin
Run till exit from #1  0xffffffffc0805b3b in zfs_ioc_userspace_many (zc=0xffff880231748000) at /usr/src/zfs/module/zfs/zfs_ioctl.c:5742
zfsdev_ioctl_common (vecnum=<optimized out>, arg=<optimized out>) at /usr/src/zfs/module/zfs/zfs_ioctl.c:7410
7410			cookie = spl_fstrans_mark();
Value returned is $3 = 95
```

`zfsvfs->z_os->os_flags` is missing `OBJSET_FLAG_USERACCOUNTING_COMPLETE`, the following patch seems to fix the issue (minimally tested):

```diff
diff --git a/module/zfs/dmu_objset.c b/module/zfs/dmu_objset.c
index 2a9464e2a..cc092cbfa 100644
--- a/module/zfs/dmu_objset.c
+++ b/module/zfs/dmu_objset.c
@@ -2321,6 +2321,7 @@ dmu_objset_id_quota_upgrade_cb(objset_t *os)
        if (err)
                return (err);
 
+       os->os_flags |= OBJSET_FLAG_USERACCOUNTING_COMPLETE;
        os->os_flags |= OBJSET_FLAG_USEROBJACCOUNTING_COMPLETE;
        if (dmu_objset_projectquota_enabled(os))
                os->os_flags |= OBJSET_FLAG_PROJECTQUOTA_COMPLETE;
```

```shell
root@linux:/usr/src/zfs# POOLNAME1='testpool1'
root@linux:/usr/src/zfs# TMPDIR='/var/tmp'
root@linux:/usr/src/zfs# mountpoint -q $TMPDIR || mount -t tmpfs tmpfs $TMPDIR
root@linux:/usr/src/zfs# zpool destroy -f $POOLNAME1
root@linux:/usr/src/zfs# rm -f $TMPDIR/zpool1.dat
root@linux:/usr/src/zfs# truncate -s 128m $TMPDIR/zpool1.dat
root@linux:/usr/src/zfs# echo 'password' | zpool create -f -O encryption=on -O keyformat=passphrase $POOLNAME1 $TMPDIR/zpool1.dat
root@linux:/usr/src/zfs# zfs create -o mountpoint=none $POOLNAME1/recv
root@linux:/usr/src/zfs# 
root@linux:/usr/src/zfs# POOLNAME2='testpool2'
root@linux:/usr/src/zfs# TMPDIR='/var/tmp'
root@linux:/usr/src/zfs# mountpoint -q $TMPDIR || mount -t tmpfs tmpfs $TMPDIR
root@linux:/usr/src/zfs# zpool destroy -f $POOLNAME2
root@linux:/usr/src/zfs# rm -f $TMPDIR/zpool2.dat
root@linux:/usr/src/zfs# truncate -s 128m $TMPDIR/zpool2.dat
root@linux:/usr/src/zfs# zpool create -f $POOLNAME2 $TMPDIR/zpool2.dat
root@linux:/usr/src/zfs# zfs create -o mountpoint=none $POOLNAME2/recv
root@linux:/usr/src/zfs# 
root@linux:/usr/src/zfs# zfs create $POOLNAME2/fs
root@linux:/usr/src/zfs# dd if=/dev/urandom of=/$POOLNAME2/fs/random1 bs=1M count=1
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.0118612 s, 88.4 MB/s
root@linux:/usr/src/zfs# zfs snap $POOLNAME2/fs@snap1
root@linux:/usr/src/zfs# zfs send $POOLNAME2/fs@snap1 | zfs recv $POOLNAME1/recv/fs -o mountpoint=/mnt
root@linux:/usr/src/zfs# zfs userspace $POOLNAME1/recv/fs
TYPE        NAME   USED  QUOTA  OBJUSED  OBJQUOTA
POSIX User  root  1.00M   none        2      none
root@linux:/usr/src/zfs# 
```

**Comment by tcaputi** [comment] 2019-10-29 18:40
I agree with @loli10K 's diagnosis and independently came to the same conclusion. I am a little concerned about how confusing the differences between useraccounting and userobjaccounting are. For instance, I'm not sure why `dmu_objset_userspace_upgrade()` and `dmu_objset_id_quota_upgrade_cb()` set different flags despite doing practically of the same work. Should we be setting the USEROBJ accounting flags in `dmu_objset_userspace_upgrade()` as well? Should these functions be combined?

I'm not sure who would be more knowledgeable in this area of the code to verify this. @behlendorf do you have any ideas?

**Comment by scratchings** [comment] 2020-11-11 14:58
Hi,

This is still a very significant issue for one of our production servers. Please could I and update as to whether this fix will be incorporated into a release.

**Closed** 2020-11-16 17:10 UTC
Labels: Component: Encryption, Type: Defect
