### ISSUE TITLE
kernel stuck and copy_user_handle_tail

### ISSUE THREAD

**Issue by justinpryzby** [openzfs/zfs#11641] opened 2021-02-23 15:28 UTC
Distribution Name	| Centos
Distribution Version | 7
Linux Kernel	| 3.10.0-1160.15.2
Architecture	| x86_64
ZFS Version	| zfs-2.0.1-1.el7.x86_64
SPL Version	| 2.0.1-1

A few times now, 2 different servers have required reboot with unkillable postgres process.
Actually, this process is running "pg_restore", since when this happened 2 weeks ago it corrupted the postgres cluster, requiring restore of terabytes data from backup.

 5538 ?      R ?        1-18:16:34 postgres: pryzbyj ts [local] CREATE INDEX

It's in a postgres "wait event" for "DataFileExtend".

Note that it's been chewing CPU for 38 hours - this process should have completed within ~20min.

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                     
 5538 postgres  20   0 1387228   3232   3232 R  99.7  0.0   2543:18 postgres: pryzbyj ts [local] CREATE INDEX                                                                                                                   

wchan shows nothing:
  PID WCHAN  S TTY          TIME COMMAND
 5538 ?      R ?        1-18:21:05 postgres: pryzbyj ts [local] CREATE INDEX

I'm not able to connect using trace/ltrace/gdb, but perf top shows:
  63.10%  [kernel]                 [k] copy_user_handle_tail                                                                                                                                                                     
   1.62%  [kernel]                 [k] avtab_search_node                                                                                                                                                                         
   1.51%  [kernel]                 [k] async_page_fault                                                                                                                                                                          
   1.37%  [kernel]                 [k] zio_create                                                                                                                                                                                
   1.30%  [kernel]                 [k] mutex_lock                                                                                                                                                                                
   1.24%  [kernel]                 [k] _raw_qspin_lock                                                                                                                                                                           
   1.12%  [kernel]                 [k] __kmalloc_node                                                                                                                                                                            
   1.06%  [kernel]                 [k] pvclock_clocksource_read                                                                                                                                                                  
   1.02%  [kernel]                 [k] _cond_resched                                                                                                                                                                             
   1.00%  [kernel]                 [k] kfree                                                                                                                                                                                     
   0.87%  [kernel]                 [k] zio_wait                                                                                                                                                                                  
   0.84%  [kernel]                 [k] __x86_indirect_thunk_rax                                                                                                                                                                  
   0.58%  [kernel]                 [k] mutex_unlock                                                                                                                                                                              

Some opened files are on the zfs "tablespace":
[pryzbyj@database ~]$ sudo ls -l /proc/5538/fd |grep zfs
lrwx------. 1 postgres postgres 64 Feb 23 23:57 39 -> /zfs/cdr_table/PG_13_202007201/3880682910/3952383708
lrwx------. 1 postgres postgres 64 Feb 23 23:57 40 -> /zfs/cdr_table/PG_13_202007201/3880682910/3952383708.1
lrwx------. 1 postgres postgres 64 Feb 23 23:57 41 -> /zfs/cdr_table/PG_13_202007201/3880682910/3952383708.2
lrwx------. 1 postgres postgres 64 Feb 23 23:57 42 -> /zfs/cdr_table/PG_13_202007201/3880682910/3952383708.3
lrwx------. 1 postgres postgres 64 Feb 23 23:57 44 -> /zfs/cdr_table/PG_13_202007201/3880682910/3952383708.4
lrwx------. 1 postgres postgres 64 Feb 23 23:57 45 -> /zfs/cdr_table/PG_13_202007201/3880682910/3952385290

I'm not sure (and the OIDs will probably be lost when I reboot and the transaction is aborted), but the *708 files might be a table, and the *290 file might be the index being created.

**Comment by justinpryzby** [comment] 2021-06-10 10:13
I haven't seen this again, and since there was no response within 3.5 months, you could close this and handle other tickets instead.

**Comment by behlendorf** [comment] 2021-06-10 15:43
@justinpryzby thanks for following up to let us know you haven't seen this again.  To my knowledge this is the only report we've had of anything like this, so the root cause is pretty unclear.  Let me close this out for the moment, but if you do observe this again by all means let us know so we can at least track it.

**Closed by behlendorf** 2021-06-10 15:43 UTC
Labels: Status: Triage Needed, Type: Defect
