### ISSUE TITLE
zfs-2.1.6 breaks boot sequence on Debian bookworm/sid

### ISSUE THREAD

**Issue by szubersk** [openzfs/zfs#14010] opened 2022-10-10 13:13 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Linux laptop.local 5.18.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1 (2022-08-10) x86_64 GNU/Linux
Distribution Version	| Linux laptop.local 5.18.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1 (2022-08-10) x86_64 GNU/Linux
Kernel Version	| Linux laptop.local 5.18.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1 (2022-08-10) x86_64 GNU/Linux
Architecture	| Linux laptop.local 5.18.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1 (2022-08-10) x86_64 GNU/Linux
OpenZFS Version	| zfs-2.1.6-1 zfs-kmod-2.1.6-1

### Describe the problem you're observing
```
Oct 10 22:01:50 laptop.local systemd[1]: Hostname set to <laptop.local>.                                                           
Oct 10 22:01:50 laptop.local systemd[1]: sysinit.target: Found ordering cycle on local-fs.target/start                             
Oct 10 22:01:50 laptop.local systemd[1]: sysinit.target: Found dependency on zfs-mount.service/start                               
Oct 10 22:01:50 laptop.local systemd[1]: sysinit.target: Found dependency on zfs-load-key.service/start                            
Oct 10 22:01:50 laptop.local systemd[1]: sysinit.target: Found dependency on basic.target/start                                    
Oct 10 22:01:50 laptop.local systemd[1]: sysinit.target: Found dependency on sysinit.target/start                                  
Oct 10 22:01:50 laptop.local systemd[1]: sysinit.target: Job local-fs.target/start deleted to break ordering cycle starting with sysinit.target/start
```

Emergency workaround:
botch `/etc/init.d/zfs-load-key` and remove `# X-Start-Before:    zfs-mount` line.

### Describe how to reproduce the problem
Boot Debian bookworm/sid with zfs-2.1.6 installed.

### Include any warning/errors/backtraces from the system logs
See above.

**Comment by gmelikov** [comment] 2022-10-11 18:21
Don't know why it didn't blast before 2.1.6, but my thought is:
- `zfs-load-key` is generated from `https://github.com/openzfs/zfs/blob/master/etc/init.d/zfs-load-key.in` via `systemd-sysv-generator`
- by default systemd adds `default.target` to all services, if `DefaultDependencies=no` wasn't explicitly set
- `default.target` usually means `all local FSes are already mounted` -> waits for `zfs-mount`, **boom, blast**
- I don't see that `systemd-sysv-generator` supports for `DefaultDependencies=no` https://github.com/systemd/systemd/blob/main/src/sysv-generator/sysv-generator.c

I can reproduce it too on Debian testing aka Bookworm update from 2.1.5 to 2.1.6

**Comment by gmelikov** [comment] 2022-10-11 18:44
Thankfully, real service file overrides sysv generator, so hotfix without breaking services start order is to copy-paste generator result and add needed line, or easier:
```
# cat > /lib/systemd/system/zfs-load-key.service
[Unit]
SourcePath=/etc/init.d/zfs-load-key
Description=Load ZFS keys for filesystems and volumes
Before=zfs-mount.service
After=zfs-import.service
DefaultDependencies=no

[Service]
Type=forking
Restart=no
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=yes
SuccessExitStatus=5 6
ExecStart=/etc/init.d/zfs-load-key start
ExecStop=/etc/init.d/zfs-load-key stop
```

**Comment by gmelikov** [comment] 2022-10-11 20:37
I was sure zfs-load-key was included in 2.1.5, but it wasn't? https://salsa.debian.org/zfsonlinux-team/zfs/-/commit/1fc2ed09cb5036e2233219cd6c6385274085c8c3

**Comment by nabijaczleweli** [comment] 2022-10-11 20:51
Why in the world is that even being included?

**Comment by gmelikov** [comment] 2022-10-11 20:56
@cdluminate looks like it's a regression in Debian downstream https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017911

**Comment by nabijaczleweli** [comment] 2022-10-11 20:57
Ha! It's because it's the only classic init script that doesn't have a basename service equivalent.

@szubersk try `ln -s /dev/null /etc/systemd/system/zfs-mount.service`, worked for me in a dry testbed

**Comment by gmelikov** [comment] 2022-10-11 21:01
@nabijaczleweli zfs-mount may be used, I think `ln -s /dev/null /etc/systemd/system/zfs-load-key.service` may be better as a one-line hotfix, or use https://github.com/openzfs/zfs/issues/14010#issuecomment-1275124584

Not sure why it was included then, it really worked via zfs-mount-generator for me on previous 2.1* releases.

**Comment by nabijaczleweli** [comment] 2022-10-11 21:06
I've updated my comment with notes for "why" – as for how we should fix it: idk, to be figured out.

For Debian, lumin@ can probably put out a -2 release with `debian/zfsutils-linux.links`:
```
/dev/null lib/systemd/system/zfs-load-key.service
```
(untested, should be equivalent to `ln -s /dev/null /lib/systemd/system/zfs-load-key.service`).

**Comment by ogelpre** [comment] 2022-10-11 21:14
I was lazy to create a systemd unit file equivalent to zfs-load-key because I don't use systemd on my machines. I didn't expect to break downstream... So yes, maybe this is a downstream issue in the first place because Debian magically handles init files. Still, I think it would be a nice to provide a systemd unit file for loading ZFS keys on boot. I'll create a separte feature request.

**Comment by nabijaczleweli** [comment] 2022-10-11 21:20
The only way to make systemd-sysv-generator skip the initscript is to make it Exist:
https://github.com/systemd/systemd/blob/8e7e4a730ba40bbc46c9d1e84207fd35781ca05a/src/sysv-generator/sysv-generator.c#L751-L762

Which we can easily do by masking it (i.e. symlinking to /dev/null). PR to be posted.

**Comment by gmelikov** [comment] 2022-10-11 21:22
Just a note - upstream deb files won't install /etc/init.d/zfs-load-keys, at least now.

**Comment by nabijaczleweli** [comment] 2022-10-11 21:27
#14019

**Comment by cdluminate** [comment] 2022-10-11 21:51
My bad. I tested the `2.1.6-1` package on my laptop before uploading. How could I have overlooked the systemd warning on boot... Thanks for notification, I'll add fix and upload a fix asap.

**Comment by cdluminate** [comment] 2022-10-11 22:05
> Just a note - upstream deb files won't install /etc/init.d/zfs-load-keys, at least now.

Yes, that packaging forked from 2.1.4-1 does not install that script, and it was fine for systemd users.

**Comment by cdluminate** [comment] 2022-10-11 22:06
> I was sure zfs-load-key was included in 2.1.5, but it wasn't? https://salsa.debian.org/zfsonlinux-team/zfs/-/commit/1fc2ed09cb5036e2233219cd6c6385274085c8c3

That true init script was missed for a while until the 2.1.6-1 upload.

**Comment by nabijaczleweli** [comment] 2022-10-11 22:08
I think systemd cracks the cycle randomly, so if you were (un)lucky it removed the one node you didn't need

**Comment by cdluminate** [comment] 2022-10-11 23:13
I have uploaded `2.1.6-2` to Debian unstable. The latest changes can be found on salsa. The update may need some time to propagate through mirrors but I think we can close this issue now.

**Closed** 2022-10-12 22:27 UTC
Labels: Type: Regression, Type: Defect

**Comment by szubersk** [comment] 2022-10-15 08:12
I confirm that `zfsutils-linux-2.1.6-2` works perfectly fine. Thank you, @cdluminate  @gmelikov @nabijaczleweli, for such a quick reaction.
