### ISSUE TITLE
Compile failure with Linux 5.5-rc2 and CONFIG_PREEMPT_RCU=y

### ISSUE THREAD

**Issue by artee666** [openzfs/zfs#9745] opened 2019-12-18 21:02 UTC
Distribution Name	|  Archlinux
Distribution Version	| current
Linux Kernel	| 5.5-rc2
Architecture	| amd64
ZFS Version	| 2019.12.13.r5590.gddb4e69db-1
SPL Version	| 2019.12.13.r5590.gddb4e69db-1

### Describe the problem you're observing
Cannot compile zfs for 5.5-rc2. There's the following error:
FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol '__rcu_read_lock'

**Comment by Ornias1993** [comment] 2019-12-18 23:21
Please be aware 5.5(rc2) isn't a supported kernel at the moment.
It might be worthwhile making an feature request issue for 5.5 kernel support instead.

**Comment by behlendorf** [comment] 2019-12-19 00:13
If I were to hazard a guess, I'd say that your kernel is built with `CONFIG_PREEMPT_RCU` which is incompatible with ZFS.  Can you check your kernel configuration to see if that is the case?  This is something we've been meaning to add a check for so it's detected at `configure` time.

**Comment by artee666** [comment] 2019-12-19 05:27
@behlendorf yes, the kernel is build with CONFIG_PREEMPT_RCU, but my current kernel 5.4.4 is build with this option as well and ZFS is working with it

**Comment by wolfgangwuerfl** [comment] 2019-12-21 09:04
@behlendorf i got the same issue, CONFIG_PREEMPT_RCU depends on CONFIG_PREEMPT, does that mean its not possible to build a full preemptive kernel since 5.5 with zfs? I switched to voluntary preemption and it the module builds without GPL incompatibility. 

Is there a plan to move the printk stuff to the SPL as a stub?

**Comment by Ornias1993** [comment] 2019-12-21 12:20
> guess the error comes

Well it isn't an error, it's linux' legally flawed way of putting licence additions into code, which may or may not be actually legally valid depending on the usecase.

Coding wise it should've been a warning, because stoping compile due to formalities just isn't best practice. But I guess it's easier to fix this than get gpl-fundementalism out of the linux codebase 👍

**Comment by XHDR** [comment] 2020-01-10 20:27
I'm not sure if something has changed, kernel wise, in between rc2 and rc5, but ZFS build fine on a locally patched kernel. I'm exporting `__rcu_read_{lock,unlock}`, just like `kernel_fpu_{begin,end}`.
Currently running kernel version `5.5-rc5`, and ZFS `0.8.0.r512.gba0ba69e5` on Arch Linux.

```
$ zgrep CONFIG_PREEMPT_RCU /proc/config.gz
CONFIG_PREEMPT_RCU=y

$ zfs list
NAME   USED  AVAIL     REFER  MOUNTPOINT
zfoo  1.00G   768M     1.00G  /zfoo
```

**Comment by Ornias1993** [comment] 2020-01-10 20:38
@XHDR So basically: Cant reproduce?

**Comment by XHDR** [comment] 2020-01-10 21:07
> @XHDR So basically: Cant reproduce?

I'm not if that's the correct term for it, as I am running a _patched_ version of 5.5-rc5, but:
**Yes**, basically.

When I've got more time on my hands, I'll try a clean, non-patched version, and see if it happens there. But for now, just experimenting with ZFS for the first time, my experience is that it seems to compile and run as it should.

**Comment by Ornias1993** [comment] 2020-01-11 11:01
Ahh, yes it seems they did the good old "Lets put something GPL-only to screw with non-gpl kernel modules just for lolz. Again.

Should be relatively easy to add this to the condom.

**Comment by freswa** [comment] 2020-01-22 20:15
@behlendorf Any chance we can get a patch into 0.8.3 and out until 5.5 becomes stable and the first user run into problems?

**Comment by behlendorf** [comment] 2020-01-22 22:12
What needs to be done is to identify which function we're calling now incidentally calls `__rcu_read_lock`.  One way to narrow down the possible functions would be to verify that unsetting `CONFIG_PREEMPT_RCU` prevents the build failure.  Then we'll be able to determine what can be done.  If would be helpful if someone could perform this test and post the results.

**Comment by tycho** [comment] 2020-01-23 05:10
The object referencing `__rcu_read_unlock` is `./module/os/linux/zfs/vdev_disk.o`. The reference chain is basically: `__rcu_read_unlock` -> `rcu_read_unlock` -> `percpu_ref_tryget` -> `blkg_tryget` -> `vdev_bio_associate_blkg`.

**Comment by rkitover** [comment] 2020-01-24 12:23
I can confirm this issue on the latest linus tree master.

I tried commenting out just `CONFIG_PREEMPT_RCU=y` in `.config`, but `make oldconfig` always puts it back. `make menuconfig` shows that this option cannot be set directly.

If you guys like, I can write a `config/kernel-rcu-is-gpl.m4` or some such to test whether `__rcu_read_lock` is a GPL symbol or not, if that would help.

**Comment by artee666** [comment] 2020-01-24 13:12
You need to set General setup -> Preemption Model to different setting than "Preemptible Kernel (Low-Latency Desktop)". For example to "Voluntary Kernel Preemption (Desktop)". Then zfs will compile just fine.

**Comment by behlendorf** [comment] 2020-01-24 17:44
@tycho thanks for the call chain, that makes sense.

**Comment by Lalufu** [comment] 2020-01-31 10:17
Reading this, if I have a non-preempt kernel (CONFIG_PREEMPT is not set), like Fedora ships by default, 5.5 should just work with zfs 0.8.3?

**Comment by ndowens** [comment] 2020-02-03 13:10
Also wanted to add, I got this issue with:5.5.1

**Comment by rkitover** [comment] 2020-02-03 23:59
For what it's worth, this incompatibility should not affect too many people as most distro kernels do not use preempt, as far as I know, and when they do it is through optional kernel packages like arch does.

**Comment by tycho** [comment] 2020-02-04 00:04
@rkitover The stock Arch kernel has CONFIG_PREEMPT and CONFIG_PREEMPT_RCU:

https://git.archlinux.org/svntogit/packages.git/tree/linux/trunk/config#n98
https://git.archlinux.org/svntogit/packages.git/tree/linux/trunk/config#n124

CONFIG_PREEMPT_VOLUNTARY is much more popular with distributions though (Fedora, SuSE, Ubuntu all use it).

**Comment by wavexx** [comment] 2020-02-04 08:32
On Tue, Feb 04 2020, Steven Noonan wrote:
> @rkitover The stock Arch kernel has CONFIG_PREEMPT and CONFIG_PREEMPT_RCU:
>
> https://git.archlinux.org/svntogit/packages.git/tree/linux/trunk/config#n98
> https://git.archlinux.org/svntogit/packages.git/tree/linux/trunk/config#n124

I'm doing the same via the linux-image-rt kernels on debian.
I've been doing that for years.

This issue though started popping up with the 5.4 series, where even the
stock image has preempt-rcu enabled.

**Comment by YaroKasear** [comment] 2020-02-04 15:59
Is there anything an end-user can do to workaround this problem? Downgrade the kernel? I'm using Arch Linux and this GPL-only nonsense is going to keep me from rebooting as this literally means I can't boot with the new kernel, rendering my system unusable.

**Comment by ndowens** [comment] 2020-02-04 16:03
I have been using the lts kernel fine

**Comment by WoefulDerelict** [comment] 2020-02-05 05:43
@YaroKasear End users on Arch Linux have two options. Your first and by far the easiest option is to use the LTS kernel. The second option is to revert the offending change in the 5.5 series via a patch and build/manage the kernel yourself. There is plenty of tooling to help you out but if you've never used the Arch Build System before this would prove quite the adventure.

**Comment by dagaz** [comment] 2020-02-05 08:54
> Is there anything an end-user can do to workaround this problem? Downgrade the kernel? I'm using Arch Linux and this GPL-only nonsense is going to keep me from rebooting as this literally means I can't boot with the new kernel, rendering my system unusable.

I think the obvious option is: Downgrade the kernel.
You can update your system, leaving out the kernel:

`pacman -Suy --ignore=linux,linux-headers`

I did it that way all previous problematic kernels until the zfs developers found a soloution.

**Comment by francoism90** [comment] 2020-02-06 09:59
Just to add one can use the [Arch Linux Archive](https://wiki.archlinux.org/index.php/Arch_Linux_Archive
) to downgrade to Linux 5.4.8.

Hope you guys can find a solution and I understand testing it with the latest kernel(s) takes time. :)

**Comment by artee666** [comment] 2020-02-06 11:19
In archlinux the linux-lts package will soon be based on 5.4.x (5.4.18 is currently in testing). And also linux-lts does not have RCU compiled in (as it is based on `No Forced Preemption (Server)` preemption model.

**Comment by francoism90** [comment] 2020-02-08 08:10
Offtopic:
@artee666 I've tried compiling `zfs-linux-lts` against `linux-lts` from testing, this however results in `Unable to build an empty module`. Do you use this package as well? :)

**Comment by artee666** [comment] 2020-02-08 08:26
@francoism90 I'm using `zfs-dkms` and unfortunately the result is the same for `linux-lts` from testing (`Unable to build an empty module`) :-(

**Comment by artee666** [comment] 2020-02-08 09:48
@francoism90 you need to upgrade also gcc, because there's new version in testing and linux-lts is built using this version... Then the zfs will compile just fine...

**Comment by yan12125** [comment] 2020-02-09 05:52
Stock Arch Linux kernel 5.4.15 (the last one before 5.5.x) has PREEMPT_RCU, and `__rcu_read_lock` is exposed as GPL-only:
```
$ ./usr/lib/modules/5.4.15-arch1-1/build/scripts/extract-ikconfig ./usr/lib/modules/5.4.15-arch1-1/vmlinuz | grep PREEMPT_RCU
CONFIG_PREEMPT_RCU=y
$ grep __rcu_read_lock ./usr/lib/modules/5.4.15-arch1-1/build/Module.symvers 
0x00000000      __rcu_read_lock         vmlinux EXPORT_SYMBOL_GPL
```
While zfs.ko could be built then. I am curious what actually makes the difference since kernel 5.5.x. After some investigation, this commit seems relevant: https://github.com/torvalds/linux/commit/9e8d42a0f7eb9056f8bdb241b91738b5a2923f4c. It makes `percpu_ref_tryget` depend on that GPL-only symbol.

**Comment by jonathonf** [comment] 2020-02-12 17:53
I've put together a very hacky patch which will prevent the need to reconfigure/recompile your kernel:

https://gitlab.manjaro.org/packages/extra/linux55-extramodules/spl_zfs/blob/rcu-patch/linux-5.5-rcu.patch

Essentially this overrides/reverts `percpu_ref_tryget` from https://github.com/torvalds/linux/commit/9e8d42a0f7eb9056f8bdb241b91738b5a2923f4c within https://github.com/zfsonlinux/zfs/blob/zfs-0.8.3/module/zfs/vdev_disk.c

It's very hacky and not tested very much beyond the fact that `zfs.ko` will compile.

Did I mention that it's very much a hack? OK.

**Comment by dreamcat4** [comment] 2020-02-13 19:01
So your patch seems to be different from these other 2 compatibility patches. Which seem to be for the newer 5.6.x release candidate kernel instead of current 5.5.x

https://github.com/zfsonlinux/zfs/pull/9961

https://github.com/zfsonlinux/zfs/pull/9961#issuecomment-585827288

My question then would be (about those other 2 patches) if they then still require the recompilation of certain kernels such as the ubuntu ones... since that is not mentioned in them it is pretty unclear whether we also need this still patched for 5.6 too.... or can wait to skip over the 5.5 kernel series entirely to get 0.8.3 working back again. Hmm my gut feeling is no these are seperate issues and this issue still needs to be fixed for kernels 5.6 too (anything 5.5 or higher).

Agree / disagree? Hmm.

**Comment by jonathonf** [comment] 2020-02-13 19:04
The 5.6 compat patches don't address the change in 5.5 behaviour, they fix other compat issues.

The above commit https://github.com/torvalds/linux/commit/9e8d42a0f7eb9056f8bdb241b91738b5a2923f4c is tagged for 5.6-rc1 so it looks to be an ongoing change.

Therefore, this issue still needs a proper fix.

**Comment by bobberb** [comment] 2020-02-14 21:14
Arch LTS is now linux-lts 5.4.19-1 and DKMS will not install.

**Comment by Whoops** [comment] 2020-02-14 21:43
@bobberb Are you using `zfs-dkms` from [archzfs](https://github.com/archzfs/archzfs) or something else?

I'm using `zfs-dkms` and update/rebooted this morning. Just double checked to verify, and I am on 5.4.19-1.

**Comment by bobberb** [comment] 2020-02-14 21:53
Building zfs-dkms from the AUR, not downloading from the archzfs repo. Will
try a reboot.

**Comment by Whoops** [comment] 2020-02-14 22:39
Uh, if your ZFS is on root I wouldn't reboot till you've got a good kernel.
I know the aur-zfs and arch zfs are not the same, but I'm not sure the differences. I'd suggest switching to the zfs in the [arch-zfs](https://wiki.archlinux.org/index.php/Unofficial_user_repositories#archzfs) pacman repo. You can either install `zfs-dkms` and risk kernel breakage like we have now, or install the `zfs-linux` and `zfs-linux-lts` packages and it'll prevent you from updating to an unsupported kernel.

**Comment by ipha** [comment] 2020-02-16 04:51
IMO the arch specific discussion is getting a bit off-topic,
In 5.4 zfs worked with `CONFIG_PREEMPT=y` and in 5.5+ it doesn't. Some distros ship this by default causing issues with 5.5+ kernels.

**Comment by bobberb** [comment] 2020-02-16 05:05
My apologies.

**Comment by joe-average-user** [comment] 2020-02-22 08:18
Just to mention that (for arch), you cannot easily switch to zfs-linux-lts coming from zfs-linux-git, as this happens probably on mounting a zfs pool:

This pool uses the following feature(s) not supported by this system:
        com.delphix:log_spacemap (Log metaslab changes on a single spacemap and flush them periodically.)
All unsupported features are only required for writing to the pool.
The pool can be imported using '-o readonly=on'.
cannot import 'tank': unsupported version or feature

**Comment by francoism90** [comment] 2020-02-27 11:18
I'm a bit confused, a PR has been merged that fixed the Linux 5.6 build issues. Does this mean OpenZFS is/will be compatible with the 5.6 kernel and not with the 5.5 kernel?

**Comment by lnicola** [comment] 2020-02-27 11:25
> I'm a bit confused, a PR has been merged that fixed the Linux 5.6 build issues. Does this mean OpenZFS is/will be compatible with the 5.6 kernel and not with the 5.5 kernel?

If you mean https://github.com/openzfs/zfs/pull/10064, it wasn't merged yet, and it fixes _different_ compatibility problems. The problem reported here is specific to `CONFIG_PREEMPT=y` which is something that most distributions aren't using, so it's less of a priority for ZFS.

**Closed** 2020-02-28 16:58 UTC
Labels: Type: Building

**Comment by behlendorf** [comment] 2020-02-28 17:22
A fix for this issue has been merged to the master branch and will be included in the next 0.8.x release.  I've also backported a version of the patch which applies cleanly to 0.8.3 if you need the fix sooner, see 2fcab8795c7c493845bfa277d44bc443802000b8.

**Comment by eli-schwartz** [comment] 2020-02-28 17:36
>  I've also backported a version of the patch which applies cleanly to 0.8.3 if you need the fix sooner

Much appreciated!

**Comment by YaroKasear** [comment] 2020-02-28 17:39
Fantastic. Thanks for this fix. I got an update from the ArchZFS repository this morning, so I am going to recompile my custom kernel to see if that included the fix.
