### ISSUE TITLE
zfs-0.8.4 Build fails on Armbian aarch64 kernel version 5.4

### ISSUE THREAD

**Issue by turkerali** [openzfs/zfs#10416] opened 2020-06-07 18:30 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Armbian (Debian based)
Distribution Version	| Buster Backports
Linux Kernel	| 5.4.43-rockchip64
Architecture	| aarch64 
ZFS Version	| zfs-0.8.4
SPL Version	| N/A

### Describe the problem you're observing
When I try to compile zfs-dkms from debian backports repository I get the following error:
  LD [M]  /var/lib/dkms/zfs/0.8.4/build/module/zfs/zfs.o
  Building modules, stage 2.
  MODPOST 8 modules
FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'preempt_schedule_notrace'
make[4]: *** [scripts/Makefile.modpost:94: __modpost] Error 1
make[3]: *** [Makefile:1616: modules] Error 2
make[3]: Leaving directory '/usr/src/linux-headers-5.4.43-rockchip64'
make[2]: *** [Makefile:30: modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/zfs/0.8.4/build/module'
make[1]: *** [Makefile:807: all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/0.8.4/build'
make: *** [Makefile:676: all] Error 2

### Describe how to reproduce the problem

1- nano /etc/apt/sources.list.d/buster-backports.list
deb http://deb.debian.org/debian buster-backports main contrib
deb-src http://deb.debian.org/debian buster-backports main contrib
2- nano /etc/apt/preferences.d/90_zfs
Package: libnvpair1linux libuutil1linux libzfs2linux libzfslinux-dev libzpool2linux python3-pyzfs pyzfs-doc spl spl-dkms zfs-dkms zfs-dracut zfs-initramfs zfs-test zfs-zed zfsutils-linux
Pin: release n=buster-backports
Pin-Priority: 990
3- apt update
4- apt install linux-headers-current-rockchip64 (from armbian repository)
5- apt install zfs-dkms

### Include any warning/errors/backtraces from the system logs

```
root@rock64:~# uname -a
Linux rock64 5.4.43-rockchip64 #20.05.2 SMP PREEMPT Tue Jun 2 22:47:34 CEST 2020 aarch64 GNU/Linux
root@rock64:~# zcat /proc/config.gz | grep CONFIG_PREEMPT
# CONFIG_PREEMPT_NONE is not set
# CONFIG_PREEMPT_VOLUNTARY is not set
CONFIG_PREEMPT=y
CONFIG_PREEMPT_COUNT=y
CONFIG_PREEMPTION=y
CONFIG_PREEMPT_RCU=y
CONFIG_PREEMPT_NOTIFIERS=y
```

**Comment by Titaniumtown** [comment] 2020-06-09 21:08
dupe of #9948 welcome to the club.

**Comment by satmandu** [comment] 2020-06-09 22:38
See https://github.com/openzfs/zfs/issues/8545

**Comment by satmandu** [comment] 2020-06-09 22:38
Workaround for personal system: https://github.com/openzfs/zfs/issues/9948#issuecomment-641615483

**Comment by Titaniumtown** [comment] 2020-06-10 00:26
thx!!

**Comment by Titaniumtown** [comment] 2020-06-10 00:26
how could this be fixed long-term?

**Comment by Titaniumtown** [comment] 2020-06-10 00:47
@satmandu is it legal (I don't know a lot about licensing) for me to package that fix on my arch linux arm repository? I just want to be sure

**Comment by turkerali** [comment] 2020-06-10 02:17
> how could this be fixed long-term?
I don't think there is an easy fix, otherwise they would have already implemented it. See:
https://github.com/openzfs/zfs/issues/8545#issuecomment-528581563
The solution from Satmandu changes the license from CDDL to GPL, so it is not legal.

**Comment by turkerali** [comment] 2020-06-10 02:22
> how could this be fixed long-term?

I don't think there is an easy fix, otherwise they would have already implemented it. See:
https://github.com/openzfs/zfs/issues/8545#issuecomment-528581563
The solution from Satmandu changes the license from CDDL to GPL, so it is not legal. A better solution would be changing CONFIG_PREEMPT to COMFIG_PREEMPT_VOLUNTARY in our kernel config file, and recompile the kernel. Hope zfs developers find an easy fix for this problem.

**Comment by Titaniumtown** [comment] 2020-06-10 03:16
thx for the tip. I added it to my arch linux arm repo, I am rebuilding all kernels now.

**Closed** 2020-09-25 20:28 UTC
Labels: Type: Building
