### ISSUE TITLE
ZFS reports incorrect file offset with O_APPEND

### ISSUE THREAD

**Issue by cperl82** [openzfs/zfs#13370] opened 2022-04-22 22:47 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| CentOS
Distribution Version	| 7.9.2009
Kernel Version	| 3.10.0-1160.62.1.el7.x86_64
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.3-1

### Describe the problem you're observing

Opening a new file with O_APPEND, writing some data and then reporting the current file position with lseek does not work as expected.  This seems to only affect older kernels as it works correctly with Rocky Linux 8.

### Describe how to reproduce the problem

Reproducer:

```
$ cat t.py 
#!/usr/bin/python3
import os
f = os.open('x', os.O_APPEND | os.O_WRONLY)
os.write(f, b"foobar")
print(f"file position is {os.lseek(f, 0, os.SEEK_CUR)}")
```
Expected (XFS):
```
$ touch x
$ ./t.py 
file position is 6
$ ./t.py 
file position is 12
$ ./t.py 
file position is 18
```

Incorrect (ZFS):
```
$ touch x
$ ./t.py 
file position is 6
$ ./t.py 
file position is 6
$ ./t.py 
file position is 6
```

### Include any warning/errors/backtraces from the system logs

There are no warnings or errors produced.

### Attempted analysis

I'm not very familar with the zfs code, but I did some preliminary analysis that I figured I would share.

If you trace the call to lseek (I was using systemtap), you can see that `flip->f_pos` is correct when tested against XFS, but incorrect when tested against ZFS.  E.g. here is what I saw (the first line is XFS, the second is ZFS, in this case my reproducer was called "foo", and I had run it a number of times):

```
$ sudo stap -vv --vp 10101 -e 'probe kernel.function("generic_file_llseek_size") { if (!(isinstr(execname(), "foo"))) next; printf("%d: %s %s %d\n", gettimeofday_ns(), thread_indent(0), ppfunc(), $file->f_pos);}'
      ...
1650663208575997829:      0 foo(7814): generic_file_llseek_size 66
1650663211124234261:      0 foo(7839): generic_file_llseek_size 6 
```

I believe what is happening is that on older kernels the `file_operations` `write` function pointer is set to `do_sync_write`, while on newer kernels it's set to `new_sync_write`.  Those lead to different call stacks, and ultimately different invocations of `generic_write_checks`.

#### `do_sync_write`

In the invocation of `generic_write_checks` from `zpl_aio_write`, a pointer to the `pos` variable is passed along, but that variable is never used again (and, since it was passed into `zpl_aio_write` as a copy and not a pointer, nothing is ever done with it).

#### `new_sync_write`

If you contrast that with the invocation of `generic_write_checks` from `zpl_generic_write_checks` (invoked from `zpl_iter_write`), there you'll see that a pointer to the `ki_pos` field of the `kiocb` is passed, and I believe that is what is updated and what ultimately makes it back up to the higher layers of the vfs to make sure the `filp->f_pos` field is set correctly.

Again, I'm not that familiar with the ZFS code, so this might be way off base, but my naive attempt at a fix would be to update the call to `generic_write_checks` from `zpl_aio_write` to pass in `&kiocb->ki_pos` as the second parameter.

**Comment by cperl82** [comment] 2022-04-25 20:35
Fwiw, I tested my proposed fix by using SystemTap to set the value of `kiocb->ki_pos` to the value of `pos` after the call to `generic_write_checks` in `zpl_aio_write` if they were different (effectively simulating what would happen if the address of `kiocb->ki_pos` was passed into `generic_write_checks` instead of the address of `pos`) and it seems to fix the issue for me.

I wrote the following SystemTap (the probe point is specific to my test system):

```
$ cat t.stp 
probe module("zfs").statement("zpl_aio_write@/usr/src/debug/zfs-2.1.3/module/os/linux/zfs/zpl_file.c:417")
{
        printf("%d: %s: %s: pos:%ld, ki_pos:%ld\n",
               gettimeofday_ns(),
               thread_indent(0),
               ppfunc(),
               $pos,
               $kiocb->ki_pos);
        if ($pos != $kiocb->ki_pos)
                set_kernel_long(&$kiocb->ki_pos, $pos);
}
$ sudo stap -vv --vp 10101 -g ./t.stp -d kernel -d zfs
... lots of output omitted ... 
```
And, with that SystemTap running, the reproducer now behaves correctly.  Again, I defer to someone who understands this code better if that is a sufficient fix or if something more principled is needed.

**Comment by behlendorf** [comment] 2022-04-26 00:04
@cperl82 thanks for catching this and running down the root cause.  Your assessment looks right to me, I've gone and opened PR which include a short explanation and effectively exactly your proposed fix.

**Comment by cperl82** [comment] 2022-04-26 12:48
@behlendorf thanks!  Since I'm not super well versed in this code, can you explain why it makes sense to use a local `pos` here, but it's fine to pass the `kiocb->ki_pos` directly in `zpl_generic_write_checks` (I believe this code path is what winds up being taken on newer kernels and was why I leaned in the direction of passing `kiocb->ki_pos` directly to `generic_write_checks`

**Comment by behlendorf** [comment] 2022-04-26 17:39
Sure thing, I chose use the `pos` argument since the expectation for the legacy `.aio_write()` callback is that it should honor the `loff_t pos` argument.  Now in practice, it doesn't matter too much since the kernel was moving towards getting rid of the `pos` argument for quite a few releases.  As part of this things were slowly transitioned to using `kiocb->ki_pos` instead, and the replacement `iter` interfaces added.

**Closed** 2022-04-27 19:56 UTC
Labels: Type: Defect
