### ISSUE TITLE
Tunable for max used space?

### ISSUE THREAD

**Issue by sempervictus** [openzfs/zfs#10410] opened 2020-06-05 20:05 UTC
IIRC this was discussed way back in the day, but i cant seem to pull up the old issue and find the ultimate conclusion. Sorry for the redundancy.

OpenZFS prevents pool writes at 96% capacity. We have pools used by video/photo companies in the 100s of T, and they are asking to make use of >99% of space since this is archival storage without working-set IO. Is there a tunable sysctl or property which we can adjust without modifying the sources any further? If not, is there any appetite for this to be a pool property such that storage pools like these archival/cold setups could make optimal use of their space? Is there some technical hurdle that prevents the use of the last 4%? What's the safe limit of "full" on a pool made of many large disks in terms of "when will it run out of slabs such that it stops being able to allocate or delete" in practice?

**Comment by rincebrain** [comment] 2020-06-06 00:38
I think what you're asking for is the ability to use more of the space ZFS reserves for critical pool operations so that you can't e.g. have too little space to delete things.

spa_slop_shift is the tunable for that - it defaults to a value of 5, which translates into 1/(2^5) = 3.2% of the pool's capacity reserved.

Be aware that it's not impossible for you to run into a situation where you can't free space because you're out of space the smaller you make this value.

**Comment by ahrens** [comment] 2020-10-01 17:52
This is a duplicate of https://github.com/openzfs/zfs/issues/3014.

**Closed by ahrens** 2020-10-01 17:52 UTC
Labels: Type: Documentation
