### ISSUE TITLE
Resilvering restart from 0% on reboot

### ISSUE THREAD

**Issue by xgiovio** [openzfs/zfs#11572] opened 2021-02-06 12:26 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Centos
Distribution Version	| 7.9
Linux Kernel	| 5.10
Architecture	| x64
ZFS Version	| 2.0.2
SPL Version	|

### Describe the problem you're observing
Resilvering restart from0 on reboot. If a disk is in resilvering state and I don't restart the os, it completes without problems.
If i restart the server, it restarts from 0% but only if the resilver process wasn't complete at the time of reboot. The date however is still reported correcty, when I added the disk for resilvering the first time.
### Include any warning/errors/backtraces from the system logs

```
pool: xpool2
 state: ONLINE
status: One or more devices is currently being resilvered.  The pool will
	continue to function, possibly in a degraded state.
action: Wait for the resilver to complete.
  scan: resilver in progress since Thu Feb  4 14:24:23 2021
	1.61T scanned at 315M/s, 81.5G issued at 15.6M/s, 5.32T total
	77.3G resilvered, 1.50% done, 4 days 02:06:31 to go

```

**Comment by behlendorf** [comment] 2021-02-09 20:18
This is a duplicate of #11572.  Please see my https://github.com/openzfs/zfs/issues/9393#issuecomment-573187623 explaining why this behavior is expected.

**Closed by behlendorf** 2021-02-09 20:18 UTC
Labels: Status: Triage Needed, Type: Defect
