### ISSUE TITLE
Add '-t <type>' flag to zfs destroy to prevent accidental destruction of non-snapshots

### ISSUE THREAD

**Issue by alexmbird** [openzfs/zfs#14499] opened 2023-02-16 09:36 UTC
### Describe the feature would like to see added to OpenZFS
`zpool list` takes a `-t <type>` flag which limits it to showing a single type of entity - for example `zfs list -t snap <dataset>` will show only snapshots.

It would be nice if other commands, most importantly `zfs destroy`, had a similar flag.

### How will this feature improve OpenZFS?

Destroying snapshots is an everyday operation, for example dropping redundant backups, and in most cases it isn't a dangerous one.  Many people will wish to automate this with scripts.  

Right now it's all too easy for a badly coded script (or for me before I've had my morning coffee!) to miss off the `@snapname` and uninentionally destroy a whole dataset.  With the `-r` flag one might even destroy multiple datasets, which would be catastrophic.

If we could do `zfs destroy -t snap ...`, to make explicit that we **only** want to destroy snapshots, a large footgun will be eliminated.

I imagine the feature will be relatively easy to implement - just check the specified target(s) really are snapshots and if not, exit with an error.

### Additional context
n/a

**Comment by mailinglists35** [comment] 2023-02-17 13:13
duplicate of https://github.com/openzfs/zfs/issues/9522

please follow that issue

**Closed** 2023-02-17 13:57 UTC
Labels: Type: Feature
