### ISSUE TITLE
unable to load zfs module : Unknown symbol in module, or unknown parameter

### ISSUE THREAD

**Issue by RichardWissink** [openzfs/zfs#11321] opened 2020-12-09 19:58 UTC
[zfs_2.0.0_configure_make.log](https://github.com/openzfs/zfs/files/5668497/zfs_2.0.0_configure_make.log)
### System information
Distribution Name	| Slackware
Distribution Version	| 14.2
Linux Kernel	| 4.4.227
Architecture	| x86_64
ZFS Version	| 2.0.0
SPL Version	| 2.0.0

### Describe the problem you're observing
I compile from source using ./autogen.sh / ./configure / make / make install  (since 0.6.2)
On 2.0.0 ./configure fails on the check with mktemp :
```
checking for sed --in-place... mktemp: cannot create temp file conftest.XXX: Invalid argument
./configure: line 16608: $tmpfile: ambiguous redirect
configure: error: /usr/bin/sed does not support in-place
```

2.0.0 : tmpfile=$(mktemp conftest.XXX)
I compared with 0.8.4 :
0.8.4 : tmp=`(umask 077 && mktemp -d "./confXXXXXX") 2>/dev/null` &&
My mktemp needs 6 X's (I think). I adapted configure and now it configures and compiles OK.

But when doing modprobe zfs :

```
modprobe zfs
modprobe: ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)
The ZFS modules are not loaded.

dmesg output :
[9855383.717173] ZFS: Unloaded module v0.8.4-1
[9855384.413350] zfs: Unknown symbol zfs_zstd_compress (err 0)
[9855384.413831] zfs: Unknown symbol zfs_zstd_decompress_level (err 0)
[9855384.414343] zfs: Unknown symbol zfs_zstd_cache_reap_now (err 0)
[9855384.414556] zfs: Unknown symbol zfs_zstd_decompress (err 0)
[9855434.946664] zfs: Unknown symbol zfs_zstd_compress (err 0)
[9855434.947981] zfs: Unknown symbol zfs_zstd_decompress_level (err 0)
[9855434.949348] zfs: Unknown symbol zfs_zstd_cache_reap_now (err 0)
[9855434.949939] zfs: Unknown symbol zfs_zstd_decompress (err 0)
```

**Comment by behlendorf** [comment] 2020-12-10 21:25
Commit 9109b89cd767165cdf24454f3c8477bb1eae2637 (PR #11269) addresses the tmpfile issue, you'll have to cherry pick it for now but we'll get it in the first point release.  As for the module issue it looks like the new `zzstd.ko` from OpenZFS 2.0 wasn't loaded for some reason.

**Comment by behlendorf** [comment] 2020-12-10 21:26
Duplicate of #11269.

**Closed by behlendorf** 2020-12-10 21:26 UTC
Labels: Type: Building
