### ISSUE TITLE
Debian on ZFS Root guide should avoid zpool.cache complications

### ISSUE THREAD

**Issue by kpfleming** [openzfs/zfs#10309] opened 2020-05-09 12:53 UTC
I've used the Debian on ZFS Root guide twice in the past couple of weeks to setup two Debian Buster systems; thanks for its existence, it made the process quite understandable!

However, I've found that it's possible to have a much simpler configuration for `bpool` and `boot/efi`, which doesn't involve additional services, legacy mountpoints, `canmount=off`, etc. I have my systems configured now to ignore any `zpool.cache` file which may exist, scan and import all pools at startup, and mount `boot/efi` after all ZFS mounts are completed.

This makes 'rescue' operations much easier, because when you boot the machine with a rescue image you can just 'zpool import -R /rescue -a' and get all pools, *including* `bpool`, imported and in the proper locations.

If there is interest in simplifying this setup guide to treat this pool as a normal pool and avoid the complications caused by zpool.cache, I'm happy to draft a modified version for review.

**Comment by colmbuckley** [comment] 2020-05-17 09:07
@rlaager what do you think?
@kpfleming Could you post a summary? In my experience, it's tricky to get everything happening in the right order on all possible hardware configurations, but it's highly likely that there is a better way than the current recommendation. (And I tend to agree that import-scan tends to be better and less confusing than import-cache.)

**Comment by kpfleming** [comment] 2020-05-17 12:29
Here's what I've got at this point, it seems to be working but of course I've not tested every possible scenario!

* Ensure that zfs-import-cache.service is never run

```
systemctl mask zfs-import-cache.service
```

* Ensure that zfs-import-scan.service runs even if /etc/zfs/zpool.cache exists

/etc/systemd/system/zfs-import-scan.service.d/override.conf
```
[Unit]
ConditionPathExists=
```

* When creating boot and root filesystems (in bpool and rpool), allow `canmount` to be defaulted instead of forcing it off

* In /etc/fstab, add `x-systemd.after=zfs-mount.service` in options field for /boot/efi filesystem

With this in place, my rpool/root filesystem (specified on kernel command line) gets mounted as the real root filesystem, then bpool/boot is mounted on /boot (by zfs-import-scan), and then /boot/efi is mounted after zfs-mount is done. Various operations (manual zpool import/export) will result in `/etc/zfs/zpool.cache` being created or updated, but that is ignored since zfs-import-cache.service is never started. If the cache file exists it gets copied into the initramfs when it is updated or created, but that hasn't caused an issue for me.

One caveat: this may only be working for me since i have a *single* filesystem mounted from rpool; I don't have additional filesystems at /var, /root, /home, etc. If I had those then zfs-import-scan would be too late to mount them I suspect, and the cache file in the initramfs would be critical for proper operation.

**Comment by colmbuckley** [comment] 2020-05-17 19:20
I think there are four distinct things going on here:

* Preferring zfs-import-scan over zfs-import-cache. I happen to agree that this is a more sustainable way to import pools; and that zpool.cache can be confusing and/or flaky. I don't know enough about the history of zpool.cache to understand whether any other principles are being violated with this change.

* Importing bpool: this is probably taken care of by switching from import-cache to import-scan. I have not been able to make this fail.

* Mounting /boot: this seems to work reliably for me; despite the documentation being unclear as to whether this can reliably happen in initramfs.

* Mounting /boot/efi: This seems sound.

I think the top-level decision is whether to switch to recommending zfs-import-scan over zfs-import-cache. If we are sure that zfs-import-scan is being used (and if we eliminate the Condition on /etc/zfs/zpool.cache as you suggest), then yes much of the rest of the configuration can be simpler.

However, if a user later switches to using zfs-import-cache, or makes a mistake with the ConditionPathExists, the system will not boot correctly without the other units. The documented approach will work and recover a working system regardless of how the zpool import was accomplished. I would suggest that this is more robust.

I'll leave the final decision up to @rlaager as the document's owner.

**Comment by kpfleming** [comment] 2020-05-17 20:52
I think you're right; the existing configuration is more compatible with 'complex' configurations, although it could use some guidance to tell the user how to ensure that any pools they add/remove are reflected properly in the cache. That's what got me headed in the simpler direction, as I created two new pools, put filesystems on them, and then no matter what I did they did not get imported/mounted at boot time, until I switched to zfs-import-scan.

Also, i attempted to use the setting in /etc/default/zfs to influence the pools which would be imported by the initramfs, but was never able to get any pool other than one which contains the root filesystem to be imported.

**Comment by rlaager** [comment] 2020-05-20 01:41
> * Preferring zfs-import-scan over zfs-import-cache. I happen to agree that this is a more sustainable way to import pools; and that zpool.cache can be confusing and/or flaky. I don't know enough about the history of zpool.cache to understand whether any other principles are being violated with this change.

This seems to me to be out of the scope of the Root-on-ZFS HOWTO. That is, this seems like more of a general ZFS thing. Personally, I think the cache file causes more trouble than it saves, but I'm not enough of an expert on the cache to know what I don't know. There have been various discussions about getting rid of the cache file, but I don't know that anyone is actively working to eliminate it.

> * Importing bpool: this is probably taken care of by switching from import-cache to import-scan. I have not been able to make this fail.

The separate service for importing boot shouldn't actually be necessary. I have it in part to avoid problems (and thus complaints). But maybe I was running into issue when testing? I intend to omit this in the version for Ubuntu 20.04. They use a separate bpool for their ZFS support, so things already definitely work out of the box there. That will likely eventually get merged into the Debian Root-on-ZFS HOWTO (whether Buster or at some future point).

> * Mounting /boot: this seems to work reliably for me; despite the documentation being unclear as to whether this can reliably happen in initramfs.

If the pool imports, this should Just Work. Is there some problem here?

> * Mounting /boot/efi: This seems sound.

This should Just Work too. The Buster HOWTO uses the ZFS generator, so systemd should be aware of `/boot` and thus order it before `/boot/efi`. There should be no need for `x-systemd.after=zfs-mount.service` if you're using the generator.

**Comment by colmbuckley** [comment] 2020-05-20 09:36
> This seems to me to be out of the scope of the Root-on-ZFS HOWTO. That is, this seems like more of a general ZFS thing. Personally, I think the cache file causes more trouble than it saves, but I'm not enough of an expert on the cache to know what I don't know. There have been various discussions about getting rid of the cache file, but I don't know that anyone is actively working to eliminate it.

I agree. The only thing I'd suggest for this doc is maybe a sidebar on "Using zfs-import-scan instead of zfs-import-cache"; calling out in particular the need to eliminate the `ConditionPathExists` restriction.

> The separate service for importing boot shouldn't actually be necessary.

Great; the only thing I might worry about is that bpool is somehow left out of zpool.cache, resulting in the system not importing this pool. I worry that there seems to be a general lack of understanding about exactly how zpool.cache works and how it interacts with multiple pools.

> > * Mounting /boot: this seems to work reliably for me; despite the documentation being unclear as to whether this can reliably happen in initramfs.
> 
> If the pool imports, this should Just Work. Is there some problem here?

See section 5.8 (and 3.2) - bpool/BOOT/debian is marked as `canmount=noauto, mountpoint=legacy` with an explicit fstab entry "until there is support for mounting /boot in the initramfs". It's not clear to me why this is needed; changing it to `canmount=on, mountpoint=/boot` and leaving out the fstab line seems to work fine for me, but perhaps there are circumstances where this would fail?

> > * Mounting /boot/efi: This seems sound.
> 
> This should Just Work too. The Buster HOWTO uses the ZFS generator, so systemd should be aware of `/boot` and thus order it before `/boot/efi`. There should be no need for `x-systemd.after=zfs-mount.service` if you're using the generator.

Mighty, thanks.

**Comment by rlaager** [comment] 2020-05-24 07:57
> See section 5.8 (and 3.2) - bpool/BOOT/debian is marked as `canmount=noauto, mountpoint=legacy` with an explicit fstab entry "until there is support for mounting /boot in the initramfs". It's not clear to me why this is needed; changing it to `canmount=on, mountpoint=/boot` and leaving out the fstab line seems to work fine for me, but perhaps there are circumstances where this would fail?

I looked into this. There was a reason for this. The idea is that `bpool/BOOT/debian` should be able to be cloned, just like `rpool/ROOT/debian`. The problem is that it doesn't really work without special support in the initramfs. Given that, it is possible to simplify this as you described. I have this change commited locally. It'll get pushed with some other changes.

The original point of this issue was about `zpool.cache` and eliminating the special service for importing bpool. I am (lightly, could be convinced otherwise) opposed to the Root on ZFS HOWTO overriding the design of the regular pool importing units (i.e. scanning when a `zpool.cache` exists). I'm also not confident enough at this time to simply drop the special service. I presumably added it for a reason, and I don't have time at the moment to do sufficient testing to be confident either way. I'm open to reconsidering this.

The HOWTO has been moved to a new openzfs/openzfs-docs repository, I am going to close this issue. If either of you want to continue this discussion, please create a new issue over at: https://github.com/openzfs/openzfs-docs/issues/new

**Closed by rlaager** 2020-05-24 07:57 UTC
