### ISSUE TITLE
kmod for latest Rocky Linux Kernel

### ISSUE THREAD

**Issue by jb-alvarado** [openzfs/zfs#15831] opened 2024-01-29 06:42 UTC
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Rock Linux 
Distribution Version	| 9.3
Kernel Version	| 5.14.0-362.18.1.el9_3.x86_64
Architecture	| x86_64
OpenZFS Version	| 2.1.14-1

### Describe the problem you're observing
After latest update the kmod kernel module is not loading anymore. Reinstalling the zfs packages makes no different.

dmesg also don't show any message about zfs. I guess the module needs a rebuild.

### Describe how to reproduce the problem
Install latest updates.

**Comment by Ichnafi** [comment] 2024-01-29 19:17
Same Problem here. Interestingly the zfs module location changed compared to previous kernel. 
Here's a "find" in my /lib/modules
```
./5.14.0-362.8.1.el9_3.x86_64/extra/zfs
./5.14.0-362.8.1.el9_3.x86_64/extra/zfs/zfs
./5.14.0-362.8.1.el9_3.x86_64/extra/zfs/zfs/zfs.ko
./5.14.0-362.13.1.el9_3.x86_64/weak-updates/zfs
./5.14.0-362.13.1.el9_3.x86_64/weak-updates/zfs/zfs
./5.14.0-362.13.1.el9_3.x86_64/weak-updates/zfs/zfs/zfs.ko
```
No idea what "weak-updates" means, but the module can not be loaded like this. 
```
modprobe zfs
```
will fail

**Comment by tmzullinger** [comment] 2024-01-30 04:22
As often as this happens in newer EL releases, I wonder if perhaps trying to build a single, stable kmod-zfs is worth the effort?

For the [nvidia-kmod](https://pkgs.rpmfusion.org/cgit/nonfree/nvidia-kmod.git/tree/nvidia-kmod.spec?h=el9), the rpmfusion folks use the [akmods](https://rpmfusion.org/Packaging/KernelModules/Akmods) tool and build for kernels as they change.  That way they don't have to build a kmod for each new kernel, but when the kABI changes and one is required, it can be built for that kernel and still installed in parallel with previous `kmod-nvidia` packages.   [See also [kmods v2 documentation](https://rpmfusion.org/Packaging/KernelModules/Kmods2).]

I don't know the specifics of how this is managed by the rpmfusion folks for releases, unfortunately.  I mention it in case someone here wants to do some research and possibly propose some patches/changes to the existing zfs-kmod spec file and build process.

It _may_ make life easier for everyone involved.  Or it may be more work than it's worth, I don't know. ;)

**Comment by jb-alvarado** [comment] 2024-01-30 06:16
I have no knowledge about building kmod modules, but maybe there is a way to automate that process? I think about some scripts which checks for updates, and every time a kernel update is coming the scripts start the build and upload process.

I think we could provide a VM for that, and maybe in long terms we found a company that donate one.

Or there is a way to use custom runner on github.

**Comment by tonyhutter** [comment] 2024-01-30 19:21
@jb-alvarado - thanks for the heads-up, I'll start building the new kmods.

> I have no knowledge about building kmod modules, but maybe there is a way to automate that process? I think about some scripts which checks for updates, and every time a kernel update is coming the scripts start the build and upload process.

The problem isn't so much automating the build but rather signing the RPMs.  We currently do the RPM signing and repo upload by hand.  You could automate that of course, but then you'd have to have trust that whatever script is auto-signing and uploading the RPMs is 100% secure.  The risk may or may not be worth it though for the automation though.

As a side note - I think that long-term we should just stop building kmods for CentOS and only build dkms like we do for Fedora.  This is doubly true since RHEL/Centos/Alma/Rocky seem to be getting more fragmented.  I don't think we're ready to pull the trigger on killing off the kmods yet though.

**Comment by tmzullinger** [comment] 2024-01-30 19:47
> As a side note - I think that long-term we should just stop building kmods for CentOS and only build dkms like we do for Fedora. This is doubly true since RHEL/Centos/Alma/Rocky seem to be getting more fragmented. I don't think we're ready to pull the trigger on killing off the kmods yet though.

That's quite understandable.  I guess I'll have to look at dkms soon.  I've used kmods and/or akmods for EL-based systems and Fedora for so long that I don't know how dkms compares these days.  I imagine it's not all that much different from akmods.  Though perhaps I'll look at making an akmod-zfs package to keep something more familiar.

Thanks for all the work in keeping up with these moving targets @tonyhutter!

**Comment by tonyhutter** [comment] 2024-01-31 23:06
I've pushed out the new kmods - closing issue.

**Closed by tonyhutter** 2024-01-31 23:06 UTC
Labels: Type: Defect
