### ISSUE TITLE
Proxmox 5.4 / Debian zfs big issue

### ISSUE THREAD

**Issue by xeucs** [openzfs/zfs#10151] opened 2020-03-24 08:43 UTC
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Proxmox (Debian stretch)
Distribution Version	|  5.4-2
Linux Kernel	|  4.15.18-26-pve
Architecture	| Single node Dual CPU Xeon Gold 5120, 256GB RAM ECC REG,  Supermicro SSG-6029P-E1CR12L/X11DPH-T, BIOS 3.2 10/22/2019
ZFS Version	|  0.7.13-pve1~bpo2
SPL Version	|  0.7.13-1

### Describe the problem you're observing
The server stops to works, all VMs (a mix of Linux and Windows) became unresponsive and I cannot stop them. The only thing that I can do is hard reboot the node. I don't know exactly how to reproduce the problem, what I know is that it occurs randomly, sometimes once every 3/4 weeks, but the last time it happened only two days after the last freeze.

### Describe how to reproduce the problem
zpool status:
```
pool: HDD-Pool
 state: ONLINE
  scan: scrub repaired 0B in 22h26m with 0 errors on Sun Mar  8 22:50:54 2020
config:

	NAME                                               STATE     READ WRITE CKSUM
	HDD-Pool                                           ONLINE       0     0     0
	  raidz2-0                                         ONLINE       0     0     0
	    scsi-35000cca26ac15b54                         ONLINE       0     0     0
	    scsi-35000cca26ad40cbc                         ONLINE       0     0     0
	    scsi-35000cca26ac4cfdc                         ONLINE       0     0     0
	    scsi-35000cca26abed87c                         ONLINE       0     0     0
	    scsi-35000cca26ad81e74                         ONLINE       0     0     0
	    scsi-35000cca26ace9470                         ONLINE       0     0     0
	logs
	  nvme-eui.334842304b3049160025384100000004-part1  ONLINE       0     0     0
	cache
	  nvme-eui.334842304b3049160025384100000004-part3  ONLINE       0     0     0

errors: No known data errors

  pool: SSD-Pool
 state: ONLINE
  scan: scrub repaired 0B in 0h34m with 0 errors on Sun Mar  8 00:58:36 2020
config:

	NAME                                               STATE     READ WRITE CKSUM
	SSD-Pool                                           ONLINE       0     0     0
	  raidz2-0                                         ONLINE       0     0     0
	    ata-SAMSUNG_MZ7KM480HMHQ-00005_S3F4NX0K604708  ONLINE       0     0     0
	    ata-SAMSUNG_MZ7KM480HMHQ-00005_S3F4NX0K604709  ONLINE       0     0     0
	    ata-SAMSUNG_MZ7KM480HMHQ-00005_S3F4NX0K604707  ONLINE       0     0     0
	    ata-SAMSUNG_MZ7KM480HMHQ-00005_S3F4NX0K604677  ONLINE       0     0     0
	    ata-SAMSUNG_MZ7KM480HMHQ-00005_S3F4NX0K604706  ONLINE       0     0     0
	    ata-SAMSUNG_MZ7KM480HMHQ-00005_S3F4NX0K604672  ONLINE       0     0     0

errors: No known data errors

  pool: rpool
 state: ONLINE
  scan: scrub repaired 0B in 0h0m with 0 errors on Sun Mar  8 00:24:18 2020
config:

	NAME        STATE     READ WRITE CKSUM
	rpool       ONLINE       0     0     0
	  mirror-0  ONLINE       0     0     0
	    sdm2    ONLINE       0     0     0
	    sdn2    ONLINE       0     0     0

errors: No known data errors
```

### Include any warning/errors/backtraces from the system logs

kern.log:
```
Mar 17 12:45:29 dt-prox1 kernel: [215168.671085] ------------[ cut here ]------------
Mar 17 12:45:29 dt-prox1 kernel: [215168.671087] kernel BUG at mm/slub.c:296!
Mar 17 12:45:29 dt-prox1 kernel: [215168.671115] invalid opcode: 0000 [#1] SMP PTI
Mar 17 12:45:29 dt-prox1 kernel: [215168.671134] Modules linked in: veth tcp_diag inet_diag ebtable_filter ebtables ip6t_REJECT nf_reject_ipv6 ip6table_filter ip6_tables ipt_REJECT nf_reject_ipv4 xt_physdev xt_tcpudp xt_comment xt_addrtype xt_multiport xt_conntrack xt_set xt_mark ip_set_hash_net ip_set iptable_filter softdog openvswitch nsh nf_conntrack_ipv6 nf_nat_ipv6 nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_defrag_ipv6 nf_nat nf_conntrack libcrc32c nfnetlink_log nfnetlink 8021q garp mrp ipmi_ssif intel_rapl skx_edac x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc aesni_intel aes_x86_64 crypto_simd glue_helper cryptd ast ttm intel_cstate intel_rapl_perf drm_kms_helper pcspkr drm i2c_algo_bit fb_sys_fops syscopyarea sysfillrect sysimgblt joydev input_leds
Mar 17 12:45:29 dt-prox1 kernel: [215168.671346]  mei_me lpc_ich shpchp mei ioatdma wmi ipmi_si ipmi_devintf ipmi_msghandler acpi_power_meter acpi_pad mac_hid vhost_net vhost tap ib_iser rdma_cm iw_cm ib_cm ib_core sunrpc iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi ip_tables x_tables autofs4 ses enclosure zfs(PO) zunicode(PO) zavl(PO) icp(PO) zcommon(PO) znvpair(PO) spl(O) btrfs xor zstd_compress raid6_pq hid_generic usbmouse usbkbd usbhid hid ixgbe igb(O) i40e mpt3sas dca raid_class ptp ahci mdio scsi_transport_sas pps_core i2c_i801 libahci
Mar 17 12:45:29 dt-prox1 kernel: [215168.671487] CPU: 40 PID: 5182 Comm: z_wr_int_5 Tainted: P           O     4.15.18-26-pve #1
Mar 17 12:45:29 dt-prox1 kernel: [215168.671511] Hardware name: Supermicro SSG-6029P-E1CR12L/X11DPH-T, BIOS 3.2 10/22/2019
Mar 17 12:45:29 dt-prox1 kernel: [215168.671537] RIP: 0010:__slab_free+0x1a2/0x330
Mar 17 12:45:29 dt-prox1 kernel: [215168.671551] RSP: 0018:ffffbebe1277ba70 EFLAGS: 00010246
Mar 17 12:45:29 dt-prox1 kernel: [215168.671567] RAX: ffff9e034815bc00 RBX: ffff9e034815bc00 RCX: 00000001802a0021
Mar 17 12:45:29 dt-prox1 kernel: [215168.671587] RDX: ffff9e034815bc00 RSI: fffff64aa82056c0 RDI: ffff9de93f407600
Mar 17 12:45:29 dt-prox1 kernel: [215168.671607] RBP: ffffbebe1277bb10 R08: 0000000000000001 R09: ffffffffc0271c2c
Mar 17 12:45:29 dt-prox1 kernel: [215168.671627] R10: ffffbebe1277bb30 R11: 00000000ffffff00 R12: ffff9e034815bc00
Mar 17 12:45:29 dt-prox1 kernel: [215168.671652] R13: ffff9de93f407600 R14: fffff64aa82056c0 R15: ffff9e034815bc00
Mar 17 12:45:29 dt-prox1 kernel: [215168.672498] FS:  0000000000000000(0000) GS:ffff9de940080000(0000) knlGS:0000000000000000
Mar 17 12:45:29 dt-prox1 kernel: [215168.673325] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Mar 17 12:45:29 dt-prox1 kernel: [215168.674136] CR2: ffffb9d30417c010 CR3: 0000002fba80a003 CR4: 00000000007626e0
Mar 17 12:45:29 dt-prox1 kernel: [215168.674921] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Mar 17 12:45:29 dt-prox1 kernel: [215168.675750] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Mar 17 12:45:29 dt-prox1 kernel: [215168.676519] PKRU: 55555554
Mar 17 12:45:29 dt-prox1 kernel: [215168.677287] Call Trace:
Mar 17 12:45:29 dt-prox1 kernel: [215168.678045]  ? __mutex_lock.isra.5+0x474/0x500
Mar 17 12:45:29 dt-prox1 kernel: [215168.678804]  ? sched_clock+0x9/0x10
Mar 17 12:45:29 dt-prox1 kernel: [215168.679553]  kmem_cache_free+0x1af/0x1e0
Mar 17 12:45:29 dt-prox1 kernel: [215168.680294]  ? kmem_cache_free+0x1af/0x1e0
Mar 17 12:45:29 dt-prox1 kernel: [215168.681026]  spl_kmem_cache_free+0x13c/0x1c0 [spl]
Mar 17 12:45:29 dt-prox1 kernel: [215168.681805]  arc_hdr_destroy+0xa7/0x1b0 [zfs]
Mar 17 12:45:29 dt-prox1 kernel: [215168.682661]  arc_freed+0x69/0xc0 [zfs]
Mar 17 12:45:29 dt-prox1 kernel: [215168.683426]  zio_free_sync+0x41/0x100 [zfs]
Mar 17 12:45:29 dt-prox1 kernel: [215168.684193]  zio_free+0x90/0xd0 [zfs]
Mar 17 12:45:29 dt-prox1 kernel: [215168.684939]  dsl_free+0x11/0x20 [zfs]
Mar 17 12:45:29 dt-prox1 kernel: [215168.685678]  dsl_dataset_block_kill+0x257/0x490 [zfs]
Mar 17 12:45:29 dt-prox1 kernel: [215168.686415]  dbuf_write_done+0x162/0x1b0 [zfs]
Mar 17 12:45:29 dt-prox1 kernel: [215168.687159]  arc_write_done+0x86/0x3f0 [zfs]
Mar 17 12:45:29 dt-prox1 kernel: [215168.687906]  zio_done+0x2d0/0xe60 [zfs]
Mar 17 12:45:29 dt-prox1 kernel: [215168.688624]  ? kfree+0x165/0x180
Mar 17 12:45:29 dt-prox1 kernel: [215168.689331]  ? spl_kmem_free+0x33/0x40 [spl]
Mar 17 12:45:29 dt-prox1 kernel: [215168.690068]  zio_execute+0x95/0xf0 [zfs]
Mar 17 12:45:29 dt-prox1 kernel: [215168.690770]  taskq_thread+0x2ae/0x4d0 [spl]
Mar 17 12:45:29 dt-prox1 kernel: [215168.691702]  ? wake_up_q+0x80/0x80
Mar 17 12:45:29 dt-prox1 kernel: [215168.692403]  ? zio_reexecute+0x390/0x390 [zfs]
Mar 17 12:45:29 dt-prox1 kernel: [215168.693068]  kthread+0x105/0x140
Mar 17 12:45:29 dt-prox1 kernel: [215168.693714]  ? task_done+0xb0/0xb0 [spl]
Mar 17 12:45:29 dt-prox1 kernel: [215168.694339]  ? kthread_create_worker_on_cpu+0x70/0x70
Mar 17 12:45:29 dt-prox1 kernel: [215168.694919]  ret_from_fork+0x35/0x40
Mar 17 12:45:29 dt-prox1 kernel: [215168.695478] Code: ff ff ff 75 5d 48 83 bd 68 ff ff ff 00 0f 84 b9 fe ff ff 48 8b b5 60 ff ff ff 48 8b bd 68 ff ff ff e8 83 b5 79 00 e9 a1 fe ff ff <0f> 0b 80 4d ab 80 4c 8b 45 88 31 d2 4c 8b 4d a8 4c 89 f6 e8 66 
Mar 17 12:45:29 dt-prox1 kernel: [215168.696635] RIP: __slab_free+0x1a2/0x330 RSP: ffffbebe1277ba70
Mar 17 12:45:29 dt-prox1 kernel: [215168.697252] ---[ end trace d6de8124ea773971 ]---
```

arc_summary:
```
------------------------------------------------------------------------
ZFS Subsystem Report				Tue Mar 24 09:41:35 2020
ARC Summary: (HEALTHY)
	Memory Throttle Count:			0

ARC Misc:
	Deleted:				157.71M
	Mutex Misses:				9.77k
	Evict Skips:				62.02k

ARC Size:				99.70%	15.95	GiB
	Target Size: (Adaptive)		100.00%	16.00	GiB
	Min Size (Hard Limit):		12.50%	2.00	GiB
	Max Size (High Water):		8:1	16.00	GiB

ARC Size Breakdown:
	Recently Used Cache Size:	54.27%	7.74	GiB
	Frequently Used Cache Size:	45.73%	6.52	GiB

ARC Hash Breakdown:
	Elements Max:				10.62M
	Elements Current:		87.07%	9.25M
	Collisions:				103.13M
	Chain Max:				7
	Chains:					1.06M

ARC Total accesses:					944.38M
	Cache Hit Ratio:		88.24%	833.31M
	Cache Miss Ratio:		11.76%	111.07M
	Actual Hit Ratio:		85.84%	810.68M

	Data Demand Efficiency:		72.40%	299.96M
	Data Prefetch Efficiency:	55.77%	56.77M

	CACHE HITS BY CACHE LIST:
	  Anonymously Used:		0.95%	7.90M
	  Most Recently Used:		18.81%	156.71M
	  Most Frequently Used:		78.48%	653.96M
	  Most Recently Used Ghost:	1.30%	10.87M
	  Most Frequently Used Ghost:	0.46%	3.86M

	CACHE HITS BY DATA TYPE:
	  Demand Data:			26.06%	217.16M
	  Prefetch Data:		3.80%	31.66M
	  Demand Metadata:		70.01%	583.41M
	  Prefetch Metadata:		0.13%	1.08M

	CACHE MISSES BY DATA TYPE:
	  Demand Data:			74.55%	82.80M
	  Prefetch Data:		22.61%	25.11M
	  Demand Metadata:		2.65%	2.94M
	  Prefetch Metadata:		0.19%	214.12k

L2 ARC Summary: (HEALTHY)
	Low Memory Aborts:			45
	Free on Write:				11.11k
	R/W Clashes:				0
	Bad Checksums:				0
	IO Errors:				0

L2 ARC Size: (Adaptive)				52.84	GiB
	Compressed:			60.51%	31.97	GiB
	Header Size:			0.92%	497.06	MiB

L2 ARC Evicts:
	Lock Retries:				872
	Upon Reading:				0

L2 ARC Breakdown:				111.06M
	Hit Ratio:			11.20%	12.44M
	Miss Ratio:			88.80%	98.63M
	Feeds:					612.77k

L2 ARC Writes:
	Writes Sent:			100.00%	570.06k

DMU Prefetch Efficiency:					163.96M
	Hit Ratio:			18.75%	30.74M
	Miss Ratio:			81.25%	133.22M



ZFS Tunables:
	dbuf_cache_hiwater_pct                            10
	dbuf_cache_lowater_pct                            10
	dbuf_cache_max_bytes                              104857600
	dbuf_cache_max_shift                              5
	dmu_object_alloc_chunk_shift                      7
	ignore_hole_birth                                 1
	l2arc_feed_again                                  1
	l2arc_feed_min_ms                                 200
	l2arc_feed_secs                                   1
	l2arc_headroom                                    2
	l2arc_headroom_boost                              200
	l2arc_noprefetch                                  0
	l2arc_norw                                        0
	l2arc_write_boost                                 8388608
	l2arc_write_max                                   8388608
	metaslab_aliquot                                  524288
	metaslab_bias_enabled                             1
	metaslab_debug_load                               0
	metaslab_debug_unload                             0
	metaslab_fragmentation_factor_enabled             1
	metaslab_lba_weighting_enabled                    1
	metaslab_preload_enabled                          1
	metaslabs_per_vdev                                200
	send_holes_without_birth_time                     1
	spa_asize_inflation                               24
	spa_config_path                                   /etc/zfs/zpool.cache
	spa_load_verify_data                              1
	spa_load_verify_maxinflight                       10000
	spa_load_verify_metadata                          1
	spa_slop_shift                                    5
	zfetch_array_rd_sz                                1048576
	zfetch_max_distance                               8388608
	zfetch_max_streams                                8
	zfetch_min_sec_reap                               2
	zfs_abd_scatter_enabled                           1
	zfs_abd_scatter_max_order                         10
	zfs_admin_snapshot                                1
	zfs_arc_average_blocksize                         8192
	zfs_arc_dnode_limit                               0
	zfs_arc_dnode_limit_percent                       10
	zfs_arc_dnode_reduce_percent                      10
	zfs_arc_grow_retry                                0
	zfs_arc_lotsfree_percent                          10
	zfs_arc_max                                       17179869184
	zfs_arc_meta_adjust_restarts                      4096
	zfs_arc_meta_limit                                0
	zfs_arc_meta_limit_percent                        75
	zfs_arc_meta_min                                  0
	zfs_arc_meta_prune                                10000
	zfs_arc_meta_strategy                             1
	zfs_arc_min                                       2147483648
	zfs_arc_min_prefetch_lifespan                     0
	zfs_arc_p_dampener_disable                        1
	zfs_arc_p_min_shift                               0
	zfs_arc_pc_percent                                0
	zfs_arc_shrink_shift                              0
	zfs_arc_sys_free                                  0
	zfs_autoimport_disable                            1
	zfs_checksums_per_second                          20
	zfs_compressed_arc_enabled                        1
	zfs_dbgmsg_enable                                 0
	zfs_dbgmsg_maxsize                                4194304
	zfs_dbuf_state_index                              0
	zfs_deadman_checktime_ms                          5000
	zfs_deadman_enabled                               1
	zfs_deadman_synctime_ms                           1000000
	zfs_dedup_prefetch                                0
	zfs_delay_min_dirty_percent                       60
	zfs_delay_scale                                   500000
	zfs_delays_per_second                             20
	zfs_delete_blocks                                 20480
	zfs_dirty_data_max                                4294967296
	zfs_dirty_data_max_max                            4294967296
	zfs_dirty_data_max_max_percent                    25
	zfs_dirty_data_max_percent                        10
	zfs_dirty_data_sync                               67108864
	zfs_dmu_offset_next_sync                          0
	zfs_expire_snapshot                               300
	zfs_flags                                         0
	zfs_free_bpobj_enabled                            1
	zfs_free_leak_on_eio                              0
	zfs_free_max_blocks                               100000
	zfs_free_min_time_ms                              1000
	zfs_immediate_write_sz                            32768
	zfs_max_recordsize                                1048576
	zfs_mdcomp_disable                                0
	zfs_metaslab_fragmentation_threshold              70
	zfs_metaslab_segment_weight_enabled               1
	zfs_metaslab_switch_threshold                     2
	zfs_mg_fragmentation_threshold                    85
	zfs_mg_noalloc_threshold                          0
	zfs_multihost_fail_intervals                      5
	zfs_multihost_history                             0
	zfs_multihost_import_intervals                    10
	zfs_multihost_interval                            1000
	zfs_multilist_num_sublists                        0
	zfs_no_scrub_io                                   0
	zfs_no_scrub_prefetch                             0
	zfs_nocacheflush                                  0
	zfs_nopwrite_enabled                              1
	zfs_object_mutex_size                             64
	zfs_pd_bytes_max                                  52428800
	zfs_per_txg_dirty_frees_percent                   30
	zfs_prefetch_disable                              0
	zfs_read_chunk_size                               1048576
	zfs_read_history                                  0
	zfs_read_history_hits                             0
	zfs_recover                                       0
	zfs_recv_queue_length                             16777216
	zfs_resilver_delay                                2
	zfs_resilver_min_time_ms                          3000
	zfs_scan_idle                                     50
	zfs_scan_ignore_errors                            0
	zfs_scan_min_time_ms                              1000
	zfs_scrub_delay                                   4
	zfs_send_corrupt_data                             0
	zfs_send_queue_length                             16777216
	zfs_sync_pass_deferred_free                       2
	zfs_sync_pass_dont_compress                       5
	zfs_sync_pass_rewrite                             2
	zfs_sync_taskq_batch_pct                          75
	zfs_top_maxinflight                               32
	zfs_txg_history                                   0
	zfs_txg_timeout                                   5
	zfs_vdev_aggregation_limit                        131072
	zfs_vdev_async_read_max_active                    3
	zfs_vdev_async_read_min_active                    1
	zfs_vdev_async_write_active_max_dirty_percent     60
	zfs_vdev_async_write_active_min_dirty_percent     30
	zfs_vdev_async_write_max_active                   10
	zfs_vdev_async_write_min_active                   2
	zfs_vdev_cache_bshift                             16
	zfs_vdev_cache_max                                16384
	zfs_vdev_cache_size                               0
	zfs_vdev_max_active                               1000
	zfs_vdev_mirror_non_rotating_inc                  0
	zfs_vdev_mirror_non_rotating_seek_inc             1
	zfs_vdev_mirror_rotating_inc                      0
	zfs_vdev_mirror_rotating_seek_inc                 5
	zfs_vdev_mirror_rotating_seek_offset              1048576
	zfs_vdev_queue_depth_pct                          1000
	zfs_vdev_raidz_impl                               [fastest] original scalar sse2 ssse3 avx2 avx512f avx512bw
	zfs_vdev_read_gap_limit                           32768
	zfs_vdev_scheduler                                noop
	zfs_vdev_scrub_max_active                         2
	zfs_vdev_scrub_min_active                         1
	zfs_vdev_sync_read_max_active                     10
	zfs_vdev_sync_read_min_active                     10
	zfs_vdev_sync_write_max_active                    10
	zfs_vdev_sync_write_min_active                    10
	zfs_vdev_write_gap_limit                          4096
	zfs_zevent_cols                                   80
	zfs_zevent_console                                0
	zfs_zevent_len_max                                896
	zil_replay_disable                                0
	zil_slog_bulk                                     786432
	zio_delay_max                                     30000
	zio_dva_throttle_enabled                          1
	zio_requeue_io_start_cut_in_line                  1
	zio_taskq_batch_pct                               75
	zvol_inhibit_dev                                  0
	zvol_major                                        230
	zvol_max_discard_blocks                           16384
	zvol_prefetch_bytes                               131072
	zvol_request_sync                                 0
	zvol_threads                                      32
	zvol_volmode                                      1
```

Help me please....

Thank you very much...

**Comment by rincebrain** [comment] 2020-03-24 17:42
You might want to try pulling ZoL 0.8 from however Proxmox pronounces Debian's backports tree, it's possible whatever underlying logic bug you're hitting has been fixed in the interim.

This looks almost identical to #8149, and the person in there found the panic went away when they removed their L2ARC and slog devices from the pool. You could try that too.

**Comment by xeucs** [comment] 2020-03-25 19:17
Okay, but is it safe to remove L2ARC on a production server while it is online? If yes, the command is:
zpool remove HDD-Pool nvme-eui.334842304b3049160025384100000004-part3

?

Thank you

**Comment by rincebrain** [comment] 2020-03-25 19:33
Yes, it should be perfectly safe to remove L2ARC or slog devices live, and that command looks correct.

**Comment by xeucs** [comment] 2020-03-25 20:37
I removed L2ARC...
I hope I have solved the problem, I will keep you updated in the next few days if the problem recurs.

Thank you very much

**Comment by siv0** [comment] 2020-03-27 16:11
> You might want to try pulling ZoL 0.8 from however Proxmox pronounces Debian's backports tree, it's possible whatever underlying logic bug you're hitting has been fixed in the interim.
Proxmox ships the ZFS modules with the kernel - you might consider upgrading to 6.1 (5.4 will be EOL soon anyways) - provides you with zfs-0.8.3 (and kernel 5.3).
(should the proposed removing of l2arc not fix the issue)

**Comment by devZer0** [comment] 2020-04-04 11:26
do you use swap and if so, is it used on top of zvol? that has known deadlock issue.

i would also recommend updating to proxmox 6.1 and see if it makes a difference.

**Comment by devZer0** [comment] 2020-04-16 20:15
can you please post an update @xeucs ? thank you!

**Comment by xeucs** [comment] 2020-04-17 08:29
Hi,

I disabled swap partition on zfs rpool, where Proxmox is installed, and as I just said, I removed L2ARC from HDD Pool. Up to mow non more issues or problems. In the next weeks I will upgrade to Proxmox 6.1...
I'll kill you update...

Thank you all

**Comment by devZer0** [comment] 2021-03-14 14:30
@xeucs , can you provide an update and/or can you please retest with proxmox 6.3 / ZoL 0.8.5 (without removing l2arc ) and report ?

**Comment by devZer0** [comment] 2021-06-09 23:50
proxmox 5.x is EOL since 2020-07   ( see https://forum.proxmox.com/threads/proxmox-ve-support-lifecycle.35755/ ) 

could you please try to reproduce with 6.4+ and report?

**Comment by devZer0** [comment] 2021-12-18 10:27
hello, any news on this @xeucs ?

proxmox 7.0 and 7.1 has been released in the meantime.

**Comment by devZer0** [comment] 2022-09-19 08:27
proxmox 7.2 is out and proxmox 6.4 is EOL.

can you please provide an update ?

**Comment by rincebrain** [comment] 2022-09-19 08:58
I think it's safe to close this as stale, given that it's not had a new report or update except asking for updates in 2.5 years...

**Closed by rincebrain** 2022-09-19 08:58 UTC
